In [1]:
import numpy as np

|||||
|:--:|:--:|:--:|:--:|
|1|2|3|4|
|5|6|7|8|
|9|10|11|12|
|13|14|15|16|

In [85]:
split_list = np.array([[14, 10, 8, 13],
                       [12, 2, 3, 6],
                       [11, 4, 9, 5],
                       [1, 15, 7, 16]])
print(split_list)

[[14 10  8 13]
 [12  2  3  6]
 [11  4  9  5]
 [ 1 15  7 16]]


In [96]:
split_list = np.array([[14, 10, 8, 13],
                       [12, 2, 3, 6],
                       [11, 4, 9, 5],
                       [1, 15, 7, 16]])
print(split_list)
print()
print("       ↓")
print()

exchange = 0

# aim_numを狙った座標まで移動する
def move(aim_num, choice_num, pos, exchange):
    aim_pos = tuple(nd[0] for nd in np.where(split_list == aim_num))
    choice_pos = tuple(nd[0] for nd in np.where(split_list == choice_num))
    
    if aim_pos[0] != 0 and aim_pos[0] != 3 and aim_pos[1] != 0 and aim_pos[1] != 3:
        #aim_numのy座標-1になるまでchoice_num(16)を縦移動
        while aim_pos[0]-1 != choice_pos[0]:
            if aim_pos[0] <= choice_pos[0]:
                np.put(split_list, [((choice_pos[0]+1) * (choice_pos[1]+1))-1], split_list[choice_pos[0]-1][choice_pos[1]])
                np.put(split_list, [((choice_pos[0]) * (choice_pos[1]+1))-1], choice_num)
            else:
                np.put(split_list, [((choice_pos[0]-1) * (choice_pos[1]-1))-1], split_list[choice_pos[0]+1][choice_pos[1]])
                np.put(split_list, [((choice_pos[0]) * (choice_pos[1]-1))-1], choice_num)
            choice_pos = tuple(nd[0] for nd in np.where(split_list == choice_num))
            exchange += 1

        #aim_numのx座標と同じになるまでcoice_num(16)を横移動
        while aim_pos[1] != choice_pos[1]:
            if aim_pos[1] < choice_pos[1]:
                np.put(split_list, [((choice_pos[0]+1) * (choice_pos[1]+1))-1], split_list[choice_pos[0]][choice_pos[1]-1])
                np.put(split_list, [((choice_pos[0]+1) * (choice_pos[1]+1))-2], choice_num)
            else:
                np.put(split_list, [((choice_pos[0]+1) * (choice_pos[1]+1))-1], split_list[choice_pos[0]][choice_pos[1]+1])
                np.put(split_list, [((choice_pos[0]+1) * (choice_pos[1]+1))], choice_num)
            choice_pos = tuple(nd[0] for nd in np.where(split_list == choice_num))
            exchange += 1

        # print("なんでだよ")

    # print("aim_pos = " + str(aim_pos))
    # print("choice_pos = " + str(choice_pos))
    # print(pos)
    print(split_list)
    
    return exchange

exchange = move(3, 16, [0, 3], exchange) 
print(exchange)

[[14 10  8 13]
 [12  2  3  6]
 [11  4  9  5]
 [ 1 15  7 16]]

       ↓

[[14 16 10  8]
 [12  2  3 13]
 [11  4  9  6]
 [ 1 15  7  5]]
5
