In [34]:
import numpy as np

|||||
|:--:|:--:|:--:|:--:|
|1|2|3|4|
|5|6|7|8|
|9|10|11|12|
|13|14|15|16|

In [35]:
split_list = np.array([[14, 10, 8, 13],
                       [12, 2, 3, 6],
                       [11, 4, 9, 5],
                       [1, 15, 7, 16]])
print(split_list)

[[14 10  8 13]
 [12  2  3  6]
 [11  4  9  5]
 [ 1 15  7 16]]


In [36]:
split_list = np.array([[14, 10, 8, 13],
                       [12, 2, 3, 6],
                       [11, 4, 9, 5],
                       [1, 15, 7, 16]])
print(split_list)
print()
print("       ↓")
print()

exchange = 0

# aim_numを狙った座標まで移動する
def move(aim_num, choice_num, pos, exchange):
    target_pos = tuple(nd[0] for nd in np.where(split_list == aim_num))
    choice_pos = tuple(nd[0] for nd in np.where(split_list == choice_num))
    
    if target_pos[0] != 0 and target_pos[0] != 3 and target_pos[1] != 0 and target_pos[1] != 3:
        #aim_numのy座標-1になるまでchoice_num(16)を縦移動
        while target_pos[0]-1 != choice_pos[0]:
            if target_pos[0] <= choice_pos[0]:
                np.put(split_list, [((choice_pos[0]+1) * (choice_pos[1]+1))-1], split_list[choice_pos[0]-1][choice_pos[1]])
                np.put(split_list, [((choice_pos[0]) * (choice_pos[1]+1))-1], choice_num)
            else:
                np.put(split_list, [((choice_pos[0]-1) * (choice_pos[1]-1))-1], split_list[choice_pos[0]+1][choice_pos[1]])
                np.put(split_list, [((choice_pos[0]) * (choice_pos[1]-1))-1], choice_num)
            choice_pos = tuple(nd[0] for nd in np.where(split_list == choice_num))
            exchange += 1

        #aim_numのx座標と同じになるまでcoice_num(16)を横移動
        while target_pos[1] != choice_pos[1]:
            if target_pos[1] < choice_pos[1]:
                np.put(split_list, [((choice_pos[0]+1) * (choice_pos[1]+1))-1], split_list[choice_pos[0]][choice_pos[1]-1])
                np.put(split_list, [((choice_pos[0]+1) * (choice_pos[1]+1))-2], choice_num)
            else:
                np.put(split_list, [((choice_pos[0]+1) * (choice_pos[1]+1))-1], split_list[choice_pos[0]][choice_pos[1]+1])
                np.put(split_list, [((choice_pos[0]+1) * (choice_pos[1]+1))], choice_num)
            choice_pos = tuple(nd[0] for nd in np.where(split_list == choice_num))
            exchange += 1

    else:
        print("その座標は厳しいよ")


    # print("target_pos = " + str(target_pos))
    # print("choice_pos = " + str(choice_pos))
    print(split_list)
    
    return exchange

exchange = move(1, 16, [0, 0], exchange) 
print(exchange)

[[14 10  8 13]
 [12  2  3  6]
 [11  4  9  5]
 [ 1 15  7 16]]

       ↓

その座標は厳しいよ
[[14 10  8 13]
 [12  2  3  6]
 [11  4  9  5]
 [ 1 15  7 16]]
0


In [93]:
split_list = np.array([[14, 12, 8, 1],
                       [13, 2, 3, 6],
                       [11, 4, 9, 5],
                       [10, 15, 7, 16]])
print(split_list)
print()
print("       ↓")
print()

exchange = 0

def move(target_num, choice_num, pos, exchange):
    target_pos = tuple(nd[0] for nd in np.where(split_list == target_num))
    choice_pos = tuple(nd[0] for nd in np.where(split_list == choice_num))


    if target_pos != pos:
        if target_pos[0] == 0:
            #targetがposの右
            if pos[1] < target_pos[1]:
                #targetの左にchoice_numを移動
                #choiceのx座標をtargetのx座標の左まで移動
                while target_pos[1]-1 != choice_pos[1]:
                    if target_pos[1] <= choice_pos[1]:
                        np.put(split_list, [4 * choice_pos[0] + choice_pos[1]], split_list[choice_pos[0]][choice_pos[1]-1])
                        np.put(split_list, [4 * choice_pos[0] + choice_pos[1] - 1], choice_num)
                    else:
                        np.put(split_list, [4 * (choice_pos[0]) + choice_pos[1]], split_list[choice_pos[0]][choice_pos[1]+1])
                        np.put(split_list, [4 * (choice_pos[0]) + choice_pos[1] + 1], choice_num)
                    target_pos = tuple(nd[0] for nd in np.where(split_list == target_num))
                    choice_pos = tuple(nd[0] for nd in np.where(split_list == choice_num))
                    exchange += 1
                #choiceのy座標をtargetと同じになるまで移動
                while target_pos[0] != choice_pos[0]:
                    np.put(split_list, [4 * choice_pos[0] + choice_pos[1]], split_list[choice_pos[0]-1][choice_pos[1]])
                    np.put(split_list, [4 * choice_pos[0] + choice_pos[1]-4], choice_num)
                    target_pos = tuple(nd[0] for nd in np.where(split_list == target_num))
                    choice_pos = tuple(nd[0] for nd in np.where(split_list == choice_num))
                    exchange += 1

                #targetをposのx座標まで移動
                while target_pos[1] != pos[1]:
                    np.put(split_list, [4 * (choice_pos[0]) + choice_pos[1]], split_list[choice_pos[0]][choice_pos[1]+1])
                    np.put(split_list, [4 * (choice_pos[0]) + choice_pos[1] + 1], choice_num)
                    target_pos = tuple(nd[0] for nd in np.where(split_list == target_num))
                    choice_pos = tuple(nd[0] for nd in np.where(split_list == choice_num))
                    exchange += 1
                    if target_pos[1] != pos[1]:
                        #targetの右下に移動
                        np.put(split_list, [4 * (choice_pos[0]) + choice_pos[1]], split_list[choice_pos[0]+1][choice_pos[1]])
                        np.put(split_list, [4 * (choice_pos[0]) + choice_pos[1] + 4], choice_num)
                        target_pos = tuple(nd[0] for nd in np.where(split_list == target_num))
                        choice_pos = tuple(nd[0] for nd in np.where(split_list == choice_num))
                        exchange += 1
                        #targetの下に移動
                        np.put(split_list, [4 * (choice_pos[0]) + choice_pos[1]], split_list[choice_pos[0]][choice_pos[1]-1])
                        np.put(split_list, [4 * (choice_pos[0]) + choice_pos[1] - 1], choice_num)
                        target_pos = tuple(nd[0] for nd in np.where(split_list == target_num))
                        choice_pos = tuple(nd[0] for nd in np.where(split_list == choice_num))
                        exchange += 1
                        #targetの左下に移動
                        np.put(split_list, [4 * (choice_pos[0]) + choice_pos[1]], split_list[choice_pos[0]][choice_pos[1]-1])
                        np.put(split_list, [4 * (choice_pos[0]) + choice_pos[1] -1], choice_num)
                        target_pos = tuple(nd[0] for nd in np.where(split_list == target_num))
                        choice_pos = tuple(nd[0] for nd in np.where(split_list == choice_num))
                        exchange += 1
                        #targetの左に移動
                        np.put(split_list, [4 * (choice_pos[0]) + choice_pos[1]], split_list[choice_pos[0]-1][choice_pos[1]])
                        np.put(split_list, [4 * (choice_pos[0]) + choice_pos[1] - 4], choice_num)
                        target_pos = tuple(nd[0] for nd in np.where(split_list == target_num))
                        choice_pos = tuple(nd[0] for nd in np.where(split_list == choice_num))
                        exchange += 1

    return exchange


exchange = move(1, 16, (0,0), exchange)
print(exchange)
print(split_list)

[[14 12  8  1]
 [13  2  3  6]
 [11  4  9  5]
 [10 15  7 16]]

       ↓

15
[[ 1 16  2  6]
 [14 13 12  8]
 [11  4  3  5]
 [10 15  9  7]]
