In [6]:
import numpy as np

In [36]:
split_list = np.array([[14, 10, 8, 13],
              [12, 2, 3, 6],
              [11, 4, 9, 5],
              [1, 15, 7, 16]])
print(split_list)

[[14 10  8 13]
 [12  2  3  6]
 [11  4  9  5]
 [ 1 15  7 16]]


In [35]:
pos = tuple(nd[0] for nd in np.where(x == 5))
print(pos)

(2, 3)
