In [1]:
import numpy as np

In [2]:
#上下左右に移動する関数
def up(target_num, choice_num, exchange):
    target_pos = tuple(nd[0] for nd in np.where(split_list == target_num))
    choice_pos = tuple(nd[0] for nd in np.where(split_list == choice_num))
    np.put(split_list, [4 * choice_pos[0] + choice_pos[1]], split_list[choice_pos[0]-1][choice_pos[1]])
    np.put(split_list, [4 * choice_pos[0] + choice_pos[1] - 4], choice_num)
    target_pos = tuple(nd[0] for nd in np.where(split_list == target_num))
    choice_pos = tuple(nd[0] for nd in np.where(split_list == choice_num))
    exchange += 1
    return target_pos, choice_pos, exchange

def down(target_num, choice_num, exchange):
    target_pos = tuple(nd[0] for nd in np.where(split_list == target_num))
    choice_pos = tuple(nd[0] for nd in np.where(split_list == choice_num))
    np.put(split_list, [4 * (choice_pos[0]) + choice_pos[1]], split_list[choice_pos[0]+1][choice_pos[1]])
    np.put(split_list, [4 * (choice_pos[0]) + choice_pos[1] + 4], choice_num)
    target_pos = tuple(nd[0] for nd in np.where(split_list == target_num))
    choice_pos = tuple(nd[0] for nd in np.where(split_list == choice_num))
    exchange += 1
    return target_pos, choice_pos, exchange

def right(target_num, choice_num, exchange):
    target_pos = tuple(nd[0] for nd in np.where(split_list == target_num))
    choice_pos = tuple(nd[0] for nd in np.where(split_list == choice_num))
    np.put(split_list, [4 * (choice_pos[0]) + choice_pos[1]], split_list[choice_pos[0]][choice_pos[1]+1])
    np.put(split_list, [4 * (choice_pos[0]) + choice_pos[1] + 1], choice_num)
    target_pos = tuple(nd[0] for nd in np.where(split_list == target_num))
    choice_pos = tuple(nd[0] for nd in np.where(split_list == choice_num))
    exchange += 1
    return target_pos, choice_pos, exchange

def left(target_num, choice_num, exchange):
    target_pos = tuple(nd[0] for nd in np.where(split_list == target_num))
    choice_pos = tuple(nd[0] for nd in np.where(split_list == choice_num))
    np.put(split_list, [4 * (choice_pos[0]) + choice_pos[1]], split_list[choice_pos[0]][choice_pos[1]-1])
    np.put(split_list, [4 * (choice_pos[0]) + choice_pos[1] -1], choice_num)
    target_pos = tuple(nd[0] for nd in np.where(split_list == target_num))
    choice_pos = tuple(nd[0] for nd in np.where(split_list == choice_num))
    exchange += 1
    return target_pos, choice_pos, exchange

In [5]:
split_list = np.array([[14, 12, 8, 1],
                       [13, 2, 3, 6],
                       [11, 4, 9, 5],
                       [10, 15, 7, 16]])
print(split_list)
print()
print("       ↓")
print()

exchange = 0

def move(target_num, choice_num, pos, exchange):
    target_pos = tuple(nd[0] for nd in np.where(split_list == target_num))
    choice_pos = tuple(nd[0] for nd in np.where(split_list == choice_num))


    if target_pos != pos:
        if target_pos[0] == 0:
            #targetがposの右
            if pos[1] <= target_pos[1]:
                #targetの左にchoice_numを移動
                #choiceのx座標をtargetのx座標の左まで移動
                while target_pos[1]-1 != choice_pos[1]:
                    if target_pos[1] <= choice_pos[1]: target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                    else: target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)

                #choiceのy座標をtargetと同じになるまで移動
                while target_pos[0] != choice_pos[0]:
                    target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)

                #targetをposのx座標まで移動
                while target_pos[1] != pos[1]:
                    target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                    if target_pos[1] != pos[1]:
                        #targetの右下に移動
                        target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                        #targetの下に移動
                        target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                        #targetの左下に移動
                        target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                        #targetの左に移動
                        target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)

    return exchange


exchange = move(1, 16, (0,0), exchange)
print(exchange)
print(split_list)

[[14 12  8  1]
 [13  2  3  6]
 [11  4  9  5]
 [10 15  7 16]]

       ↓

15
[[ 1 16  2  6]
 [14 13 12  8]
 [11  4  3  5]
 [10 15  9  7]]


In [7]:
#これをメインの処理にする

split_list = np.array([[14, 12, 8, 1],
                       [13, 2, 3, 6],
                       [11, 4, 9, 5],
                       [10, 15, 7, 16]])
print(split_list)
print()
print("       ↓")
print()

exchange = 0

def move(split_list):
    columns = split_list.shape[0]
    row = split_list.shape[1]

    #最後2行を除いて並び替え（たくと）
    for i in range(columns - 2):
        for j in range(row):



    #さいごの2行（たいち）
    




[[14 12  8  1]
 [13  2  3  6]
 [11  4  9  5]
 [10 15  7 16]]

       ↓

4
