In [83]:
import numpy as np
import random
import copy

#上下左右に移動する関数
def up(target_num, choice_num, exchange_num, exchange_operation):
    target_pos = tuple(nd[0] for nd in np.where(split_list == target_num))
    choice_pos = tuple(nd[0] for nd in np.where(split_list == choice_num))

    np.put(split_list, [4 * choice_pos[0] + choice_pos[1]], split_list[choice_pos[0]-1][choice_pos[1]])
    np.put(split_list, [4 * choice_pos[0] + choice_pos[1] - 4], choice_num)
    
    target_pos = tuple(nd[0] for nd in np.where(split_list == target_num))
    choice_pos = tuple(nd[0] for nd in np.where(split_list == choice_num))
    
    exchange_num += 1
    exchange_operation = exchange_operation + 'U'

    return target_pos, choice_pos, exchange_num, exchange_operation

def down(target_num, choice_num, exchange_num, exchange_operation):
    target_pos = tuple(nd[0] for nd in np.where(split_list == target_num))
    choice_pos = tuple(nd[0] for nd in np.where(split_list == choice_num))

    np.put(split_list, [4 * (choice_pos[0]) + choice_pos[1]], split_list[choice_pos[0]+1][choice_pos[1]])
    np.put(split_list, [4 * (choice_pos[0]) + choice_pos[1] + 4], choice_num)
    
    target_pos = tuple(nd[0] for nd in np.where(split_list == target_num))
    choice_pos = tuple(nd[0] for nd in np.where(split_list == choice_num))

    exchange_num += 1
    exchange_operation = exchange_operation + 'D'

    return target_pos, choice_pos, exchange_num, exchange_operation

def right(target_num, choice_num, exchange_num, exchange_operation):
    target_pos = tuple(nd[0] for nd in np.where(split_list == target_num))
    choice_pos = tuple(nd[0] for nd in np.where(split_list == choice_num))

    np.put(split_list, [4 * (choice_pos[0]) + choice_pos[1]], split_list[choice_pos[0]][choice_pos[1]+1])
    np.put(split_list, [4 * (choice_pos[0]) + choice_pos[1] + 1], choice_num)
    
    target_pos = tuple(nd[0] for nd in np.where(split_list == target_num))
    choice_pos = tuple(nd[0] for nd in np.where(split_list == choice_num))

    exchange_num += 1
    exchange_operation = exchange_operation + 'R'

    return target_pos, choice_pos, exchange_num, exchange_operation

def left(target_num, choice_num, exchange_num, exchange_operation):
    target_pos = tuple(nd[0] for nd in np.where(split_list == target_num))
    choice_pos = tuple(nd[0] for nd in np.where(split_list == choice_num))

    np.put(split_list, [4 * (choice_pos[0]) + choice_pos[1]], split_list[choice_pos[0]][choice_pos[1]-1])
    np.put(split_list, [4 * (choice_pos[0]) + choice_pos[1] -1], choice_num)
    
    target_pos = tuple(nd[0] for nd in np.where(split_list == target_num))
    choice_pos = tuple(nd[0] for nd in np.where(split_list == choice_num))

    exchange_num += 1
    exchange_operation = exchange_operation + 'L'

    return target_pos, choice_pos, exchange_num, exchange_operation




#並び替え関数
def move(split_list, exchange_num):
    columns = split_list.shape[0]
    row = split_list.shape[1]

    exchange_operation = ""

    choice_num = columns * row
    choice_pos = tuple(nd[0] for nd in np.where(split_list == choice_num))
    selection_image_position = choice_pos

    #最後2行を除いて並び替え（たくと）
    for i in range(columns - 2):
        for j in range(row):
            target_num = i * row + j + 1

            target_pos = tuple(nd[0] for nd in np.where(split_list == target_num))
            choice_pos = tuple(nd[0] for nd in np.where(split_list == choice_num))

            print("target_num = " + str(target_num) + "----------------------------------------------------------")

            #最終的に置きたい座標
            if target_num % row == 0: pos = (target_num // row - 1, row - 1)
            else: pos = (target_num // row, target_num % row - 1)

            #targetが下端でない
            if target_pos[0] != columns-1:
                #右2列を除いた列を並び替え
                if j != row - 1 and j != row - 2:
                    #targetが最終的に置きたいx座標よりも右
                    if target_pos[1] > pos[1]:
                        #targetの左下にchoice(16)を置く
                        if target_pos[1] <= choice_pos[1]:
                            while target_pos[1]-1 != choice_pos[1]:
                                target_pos, choice_pos, exchange_num, exchange_operation = left(target_num, choice_num, exchange_num, exchange_operation)
                        else:
                            while target_pos[1]-1 != choice_pos[1]:
                                target_pos, choice_pos, exchange_num, exchange_operation = right(target_num, choice_num, exchange_num, exchange_operation)
                        #targetを最終的に置きたいy座標に移動
                        if target_pos[0] < choice_pos[0]:
                            while target_pos[0]+1 != choice_pos[0]:
                                target_pos, choice_pos, exchange_num, exchange_operation = up(target_num, choice_num, exchange_num, exchange_operation)
                        else:
                            while target_pos[0]+1 != choice_pos[0]:
                                target_pos, choice_pos, exchange_num, exchange_operation = down(target_num, choice_num, exchange_num, exchange_operation)

                        #targetを置きたい座標のx座標と同じになるまで移動
                        if target_pos[1] != pos[1]:
                            target_pos, choice_pos, exchange_num, exchange_operation = up(target_num, choice_num, exchange_num, exchange_operation)
                            target_pos, choice_pos, exchange_num, exchange_operation = right(target_num, choice_num, exchange_num, exchange_operation)
                            while target_pos[1] != pos[1]:
                                target_pos, choice_pos, exchange_num, exchange_operation = down(target_num, choice_num, exchange_num, exchange_operation)
                                target_pos, choice_pos, exchange_num, exchange_operation = left(target_num, choice_num, exchange_num, exchange_operation)
                                target_pos, choice_pos, exchange_num, exchange_operation = left(target_num, choice_num, exchange_num, exchange_operation)
                                target_pos, choice_pos, exchange_num, exchange_operation = up(target_num, choice_num, exchange_num, exchange_operation)
                                target_pos, choice_pos, exchange_num, exchange_operation = right(target_num, choice_num, exchange_num, exchange_operation)
                    
                    #targetを最終的に置きたいx座標よりも左
                    elif target_pos[1] < pos[1]:
                        #targetの右下にchoice(16)を置く
                        if target_pos[1] >= choice_pos[1]:
                            while target_pos[1]+1 != choice_pos[1]:
                                target_pos, choice_pos, exchange_num, exchange_operation = right(target_num, choice_num, exchange_num, exchange_operation)
                        else:
                            while target_pos[1]+1 != choice_pos[1]:
                                target_pos, choice_pos, exchange_num, exchange_operation = left(target_num, choice_num, exchange_num, exchange_operation)
                        while target_pos[0]+1 != choice_pos[0]:
                            target_pos, choice_pos, exchange_num, exchange_operation = up(target_num, choice_num, exchange_num, exchange_operation)
                        #targetを置きたい座標のx座標と同じになるまで移動
                        if target_pos[1] != pos[1]:
                            target_pos, choice_pos, exchange_num, exchange_operation = up(target_num, choice_num, exchange_num, exchange_operation)
                            target_pos, choice_pos, exchange_num, exchange_operation = left(target_num, choice_num, exchange_num, exchange_operation)
                            while target_pos[1] != pos[1]:
                                target_pos, choice_pos, exchange_num, exchange_operation = down(target_num, choice_num, exchange_num, exchange_operation)
                                target_pos, choice_pos, exchange_num, exchange_operation = right(target_num, choice_num, exchange_num, exchange_operation)
                                target_pos, choice_pos, exchange_num, exchange_operation = right(target_num, choice_num, exchange_num, exchange_operation)
                                target_pos, choice_pos, exchange_num, exchange_operation = up(target_num, choice_num, exchange_num, exchange_operation)
                                target_pos, choice_pos, exchange_num, exchange_operation = left(target_num, choice_num, exchange_num, exchange_operation)
                            #targetの右にchoice(16)をおく
                            target_pos, choice_pos, exchange_num, exchange_operation = down(target_num, choice_num, exchange_num, exchange_operation)
                            target_pos, choice_pos, exchange_num, exchange_operation = right(target_num, choice_num, exchange_num, exchange_operation)
                            target_pos, choice_pos, exchange_num, exchange_operation = right(target_num, choice_num, exchange_num, exchange_operation)
                            target_pos, choice_pos, exchange_num, exchange_operation = up(target_num, choice_num, exchange_num, exchange_operation)
                        
                    
                    #targetが最終的に置きたいx座標と同じ
                    elif target_pos[1] == pos[1]:
                        #targetの右にchoice(16)をおく
                        #targetよりchoiceが右
                        if target_pos[1] < choice_pos[1]:
                            while target_pos[1]+1 != choice_pos[1]:
                                target_pos, choice_pos, exchange_num, exchange_operation = left(target_num, choice_num, exchange_num, exchange_operation)
                            #targetよりchoiceが上
                            if target_pos[0] > choice_pos[0]:
                                while target_pos[0] != choice_pos[0]:
                                    target_pos, choice_pos, exchange_num, exchange_operation = down(target_num, choice_num, exchange_num, exchange_operation)
                            #targetよりchoiceが下
                            else:
                                while target_pos[0] != choice_pos[0]:
                                    target_pos, choice_pos, exchange_num, exchange_operation = up(target_num, choice_num, exchange_num, exchange_operation)

                        #targetよりchoiceが左
                        elif target_pos[1] > choice_pos[1]:
                            #targetがchoiceより上or下
                            if target_pos[0] != choice_pos[0]:
                                while target_pos[1]+1 != choice_pos[1]:
                                    target_pos, choice_pos, exchange_num, exchange_operation = right(target_num, choice_num, exchange_num, exchange_operation)
                                #targetよりchoiceが上
                                if target_pos[0] > choice_pos[0]:
                                    while target_pos[0] != choice_pos[0]:
                                        target_pos, choice_pos, exchange_num, exchange_operation = down(target_num, choice_num, exchange_num, exchange_operation)
                                #targetよりchoiceが下
                                else:
                                    while target_pos[0] != choice_pos[0]:
                                        target_pos, choice_pos, exchange_num, exchange_operation = up(target_num, choice_num, exchange_num, exchange_operation)
                            #targetがchoiceと同じx座標
                            else:
                                target_pos, choice_pos, exchange_num, exchange_operation = down(target_num, choice_num, exchange_num, exchange_operation)
                                while target_pos[1]+1 != choice_pos[1]:
                                    target_pos, choice_pos, exchange_num, exchange_operation = right(target_num, choice_num, exchange_num, exchange_operation)
                                target_pos, choice_pos, exchange_num, exchange_operation = up(target_num, choice_num, exchange_num, exchange_operation)
                        
                        #targetとchoiceのx座標が同じ
                        else:
                            target_pos, choice_pos, exchange_num, exchange_operation = right(target_num, choice_num, exchange_num, exchange_operation)
                            #targetよりchoiceが上
                            if target_pos[0] > choice_pos[0]:
                                while target_pos[0] != choice_pos[0]:
                                    target_pos, choice_pos, exchange_num, exchange_operation = down(target_num, choice_num, exchange_num, exchange_operation)
                            #targetよりchoiceが下
                            else:
                                while target_pos[0] != choice_pos[0]:
                                    target_pos, choice_pos, exchange_num, exchange_operation = up(target_num, choice_num, exchange_num, exchange_operation)

                         
                    #targetを置きたい座標のy座標と同じになるまで移動
                    if target_pos[0] != pos[0]:
                        target_pos, choice_pos, exchange_num, exchange_operation = up(target_num, choice_num, exchange_num, exchange_operation)
                        target_pos, choice_pos, exchange_num, exchange_operation = left(target_num, choice_num, exchange_num, exchange_operation)
                        target_pos, choice_pos, exchange_num, exchange_operation = down(target_num, choice_num, exchange_num, exchange_operation)
                        while target_pos[0] != pos[0]:
                            target_pos, choice_pos, exchange_num, exchange_operation = right(target_num, choice_num, exchange_num, exchange_operation)
                            target_pos, choice_pos, exchange_num, exchange_operation = up(target_num, choice_num, exchange_num, exchange_operation)
                            target_pos, choice_pos, exchange_num, exchange_operation = up(target_num, choice_num, exchange_num, exchange_operation)
                            target_pos, choice_pos, exchange_num, exchange_operation = left(target_num, choice_num, exchange_num, exchange_operation)
                            target_pos, choice_pos, exchange_num, exchange_operation = down(target_num, choice_num, exchange_num, exchange_operation)
                
                #最終的に置きたい位置が右から2列目
                elif j == row - 2:
                    #最終的に置きたい座標にある
                    if target_pos[0] == pos[0] and target_pos[1] == pos[1]:
                        while target_pos[1]+1 != choice_pos[1]:
                            target_pos, choice_pos, exchange_num, exchange_operation = right(target_num, choice_num, exchange_num, exchange_operation)
                        while target_pos[0] != choice_pos[0]:
                            target_pos, choice_pos, exchange_num, exchange_operation = up(target_num, choice_num, exchange_num, exchange_operation)
                        target_pos, choice_pos, exchange_num, exchange_operation = left(target_num, choice_num, exchange_num, exchange_operation)

                    #最終的に置きたいy座標でない
                    elif target_pos[0] != pos[0]:
                        #最終的におきたいx座標でない
                        if target_pos[1] != pos[1]+1:
                            #targetよりも下にchoiceがある
                            if target_pos[0] < choice_pos[0]:
                                while target_pos[0]+1 != choice_pos[0]:
                                    target_pos, choice_pos, exchange_num, exchange_operation = up(target_num, choice_num, exchange_num, exchange_operation)
                            #targetよりも上にchoiceがある
                            elif target_pos[0] > choice_pos[0]:
                                while target_pos[0]+1 != choice_pos[0]:
                                    target_pos, choice_pos, exchange_num, exchange_operation = down(target_num, choice_num, exchange_num, exchange_operation)

                            #targetの右にchoiceを移動
                            #targetよりも右にchoiceがある
                            if target_pos[1] < choice_pos[1]:
                                while target_pos[1]+1 != choice_pos[1]:
                                    target_pos, choice_pos, exchange_num, exchange_operation = left(target_num, choice_num, exchange_num, exchange_operation)
                            #targetよりも左にchoiceがある
                            else:
                                while target_pos[1]+1 != choice_pos[1]:
                                    target_pos, choice_pos, exchange_num, exchange_operation = right(target_num, choice_num, exchange_num, exchange_operation)
                            
                            
                            #targetを右端まで移動
                            target_pos, choice_pos, exchange_num, exchange_operation = up(target_num, choice_num, exchange_num, exchange_operation)
                            target_pos, choice_pos, exchange_num, exchange_operation = left(target_num, choice_num, exchange_num, exchange_operation)
                            while target_pos[1] != pos[1]+1:
                                target_pos, choice_pos, exchange_num, exchange_operation = down(target_num, choice_num, exchange_num, exchange_operation)
                                target_pos, choice_pos, exchange_num, exchange_operation = right(target_num, choice_num, exchange_num, exchange_operation)
                                target_pos, choice_pos, exchange_num, exchange_operation = right(target_num, choice_num, exchange_num, exchange_operation)
                                target_pos, choice_pos, exchange_num, exchange_operation = up(target_num, choice_num, exchange_num, exchange_operation)
                                target_pos, choice_pos, exchange_num, exchange_operation = left(target_num, choice_num, exchange_num, exchange_operation)
                            #targetを最終的に置きたいy座標まで移動
                            target_pos, choice_pos, exchange_num, exchange_operation = up(target_num, choice_num, exchange_num, exchange_operation)
                            target_pos, choice_pos, exchange_num, exchange_operation = right(target_num, choice_num, exchange_num, exchange_operation)
                            target_pos, choice_pos, exchange_num, exchange_operation = down(target_num, choice_num, exchange_num, exchange_operation)
                            while target_pos[0] != pos[0]:
                                target_pos, choice_pos, exchange_num, exchange_operation = left(target_num, choice_num, exchange_num, exchange_operation)
                                target_pos, choice_pos, exchange_num, exchange_operation = up(target_num, choice_num, exchange_num, exchange_operation)
                                target_pos, choice_pos, exchange_num, exchange_operation = up(target_num, choice_num, exchange_num, exchange_operation)
                                target_pos, choice_pos, exchange_num, exchange_operation = right(target_num, choice_num, exchange_num, exchange_operation)
                                target_pos, choice_pos, exchange_num, exchange_operation = down(target_num, choice_num, exchange_num, exchange_operation)

                        #最終的におきたいx座標にある
                        elif target_pos[1] == pos[1]+1: 
                            #targetのx座標の左にchoiceを移動
                            if target_pos[1] == choice_pos[1]:
                                target_pos, choice_pos, exchange_num, exchange_operation = left(target_num, choice_num, exchange_num, exchange_operation)
                            else:
                                while target_pos[1]-1 != choice_pos[1]:
                                    target_pos, choice_pos, exchange_num, exchange_operation = right(target_num, choice_num, exchange_num, exchange_operation)

                            #targetの左上に移動
                            #targetよりも下にchoiceがある
                            if target_pos[0] <= choice_pos[0]:
                                while target_pos[0]-1 != choice_pos[0]:
                                    target_pos, choice_pos, exchange_num, exchange_operation = up(target_num, choice_num, exchange_num, exchange_operation)
                            #targetよりも上にchoiceがある
                            else:
                                while target_pos[0]-1 != choice_pos[0]:
                                    target_pos, choice_pos, exchange_num, exchange_operation = down(target_num, choice_num, exchange_num, exchange_operation)

                            #targetを最終的に置きたいy座標まで移動
                            target_pos, choice_pos, exchange_num, exchange_operation = right(target_num, choice_num, exchange_num, exchange_operation)
                            target_pos, choice_pos, exchange_num, exchange_operation = down(target_num, choice_num, exchange_num, exchange_operation)
                            while target_pos[0] != pos[0]:
                                target_pos, choice_pos, exchange_num, exchange_operation = left(target_num, choice_num, exchange_num, exchange_operation)
                                target_pos, choice_pos, exchange_num, exchange_operation = up(target_num, choice_num, exchange_num, exchange_operation)
                                target_pos, choice_pos, exchange_num, exchange_operation = up(target_num, choice_num, exchange_num, exchange_operation)
                                target_pos, choice_pos, exchange_num, exchange_operation = right(target_num, choice_num, exchange_num, exchange_operation)
                                target_pos, choice_pos, exchange_num, exchange_operation = down(target_num, choice_num, exchange_num, exchange_operation)


                #最終的に置きたい位置が右端
                elif j == row - 1:

                    #逆順に並んでいる
                    if target_pos[0] == pos[0] and target_pos[1] == pos[1]-1:
                        target_pos, choice_pos, exchange_num, exchange_operation = up(target_num, choice_num, exchange_num, exchange_operation)
                        target_pos, choice_pos, exchange_num, exchange_operation = left(target_num, choice_num, exchange_num, exchange_operation)
                        target_pos, choice_pos, exchange_num, exchange_operation = down(target_num, choice_num, exchange_num, exchange_operation)
                        target_pos, choice_pos, exchange_num, exchange_operation = right(target_num, choice_num, exchange_num, exchange_operation)
                        target_pos, choice_pos, exchange_num, exchange_operation = down(target_num, choice_num, exchange_num, exchange_operation)
                        target_pos, choice_pos, exchange_num, exchange_operation = left(target_num, choice_num, exchange_num, exchange_operation)
                        target_pos, choice_pos, exchange_num, exchange_operation = up(target_num, choice_num, exchange_num, exchange_operation)
                        target_pos, choice_pos, exchange_num, exchange_operation = up(target_num, choice_num, exchange_num, exchange_operation)
                        target_pos, choice_pos, exchange_num, exchange_operation = right(target_num, choice_num, exchange_num, exchange_operation)
                        target_pos, choice_pos, exchange_num, exchange_operation = down(target_num, choice_num, exchange_num, exchange_operation)
                        target_pos, choice_pos, exchange_num, exchange_operation = left(target_num, choice_num, exchange_num, exchange_operation)
                        target_pos, choice_pos, exchange_num, exchange_operation = down(target_num, choice_num, exchange_num, exchange_operation)
                        target_pos, choice_pos, exchange_num, exchange_operation = right(target_num, choice_num, exchange_num, exchange_operation)
                        target_pos, choice_pos, exchange_num, exchange_operation = up(target_num, choice_num, exchange_num, exchange_operation)
                        target_pos, choice_pos, exchange_num, exchange_operation = up(target_num, choice_num, exchange_num, exchange_operation)
                        target_pos, choice_pos, exchange_num, exchange_operation = left(target_num, choice_num, exchange_num, exchange_operation)
                        target_pos, choice_pos, exchange_num, exchange_operation = down(target_num, choice_num, exchange_num, exchange_operation)

                    #targetがtarget-1の下
                    elif target_pos[0] == pos[0]+1 and target_pos[1] == pos[1]:
                        #targetの左にchoice
                        #targetの左の座標に移動
                        if target_pos[1] > choice_pos[1]:
                            while target_pos[1]-1 != choice_pos[1]:
                                target_pos, choice_pos, exchange_num, exchange_operation = right(target_num, choice_num, exchange_num, exchange_operation)
                        else:
                            while target_pos[1]-1 != choice_pos[1]:
                                target_pos, choice_pos, exchange_num, exchange_operation = left(target_num, choice_num, exchange_num, exchange_operation)
                        #targetの左上に移動
                        if target_pos[0] < choice_pos[0]:
                            while target_pos[0]-1 != choice_pos[0]:
                                target_pos, choice_pos, exchange_num, exchange_operation = up(target_num, choice_num, exchange_num, exchange_operation)
                        
                        #3,4を最終的に置きたい座標となるよう移動
                        target_pos, choice_pos, exchange_num, exchange_operation = right(target_num, choice_num, exchange_num, exchange_operation)
                        target_pos, choice_pos, exchange_num, exchange_operation = down(target_num, choice_num, exchange_num, exchange_operation)

                    elif target_pos[0] != pos[0]+1 or target_pos[1] != pos[1]:
                        #targetの上にchoiceがある
                        if target_pos[0] > choice_pos[0]:
                            while target_pos[0]+1 != choice_pos[0]:
                                target_pos, choice_pos, exchange_num, exchange_operation = down(target_num, choice_num, exchange_num, exchange_operation)
                        #targetの下にchoiceがある
                        else:
                            while target_pos[0]+1 != choice_pos[0]:
                                target_pos, choice_pos, exchange_num, exchange_operation = up(target_num, choice_num, exchange_num, exchange_operation) 

                        #targetの右にchoiceがある
                        if target_pos[1] < choice_pos[1]:
                            while target_pos[1] != choice_pos[1]:
                                target_pos, choice_pos, exchange_num, exchange_operation = left(target_num, choice_num, exchange_num, exchange_operation)
                        #targetの左にchoiceがある
                        elif target_pos[1] > choice_pos[1]:
                            while target_pos[1] != choice_pos[1]:
                                target_pos, choice_pos, exchange_num, exchange_operation = right(target_num, choice_num, exchange_num, exchange_operation)

                        

                        #targetを右端まで移動
                        if target_pos[1] != pos[1]:
                            target_pos, choice_pos, exchange_num, exchange_operation = right(target_num, choice_num, exchange_num, exchange_operation)
                            target_pos, choice_pos, exchange_num, exchange_operation = up(target_num, choice_num, exchange_num, exchange_operation)
                            target_pos, choice_pos, exchange_num, exchange_operation = left(target_num, choice_num, exchange_num, exchange_operation)
                        else:
                            target_pos, choice_pos, exchange_num, exchange_operation = left(target_num, choice_num, exchange_num, exchange_operation)
                            target_pos, choice_pos, exchange_num, exchange_operation = up(target_num, choice_num, exchange_num, exchange_operation)
                        while target_pos[1] != pos[1]:
                            target_pos, choice_pos, exchange_num, exchange_operation = down(target_num, choice_num, exchange_num, exchange_operation)
                            target_pos, choice_pos, exchange_num, exchange_operation = right(target_num, choice_num, exchange_num, exchange_operation)
                            target_pos, choice_pos, exchange_num, exchange_operation = right(target_num, choice_num, exchange_num, exchange_operation)
                            target_pos, choice_pos, exchange_num, exchange_operation = up(target_num, choice_num, exchange_num, exchange_operation)
                            target_pos, choice_pos, exchange_num, exchange_operation = left(target_num, choice_num, exchange_num, exchange_operation)

                        #targetをtarget-1の下に移動
                        if target_pos[0] != pos[0]+1:
                            while target_pos[0] != pos[0]+1:
                                target_pos, choice_pos, exchange_num, exchange_operation = up(target_num, choice_num, exchange_num, exchange_operation)
                                target_pos, choice_pos, exchange_num, exchange_operation = right(target_num, choice_num, exchange_num, exchange_operation)
                                target_pos, choice_pos, exchange_num, exchange_operation = down(target_num, choice_num, exchange_num, exchange_operation)
                                target_pos, choice_pos, exchange_num, exchange_operation = left(target_num, choice_num, exchange_num, exchange_operation)
                                target_pos, choice_pos, exchange_num, exchange_operation = up(target_num, choice_num, exchange_num, exchange_operation)

                        #3,4を最終的に置きたい座標となるよう移動
                        target_pos, choice_pos, exchange_num, exchange_operation = up(target_num, choice_num, exchange_num, exchange_operation)
                        target_pos, choice_pos, exchange_num, exchange_operation = right(target_num, choice_num, exchange_num, exchange_operation)
                        target_pos, choice_pos, exchange_num, exchange_operation = down(target_num, choice_num, exchange_num, exchange_operation)
                        target_pos, choice_pos, exchange_num, exchange_operation = left(target_num, choice_num, exchange_num, exchange_operation)                 


            #targetが下端
            else:
                #右2列を除いた列を並び替え
                if j != row - 1 and j != row - 2:
                    #targetが最終的におきたいx座標よりも右
                    if target_pos[1] > pos[1]:
                        #targetの上の座標にchoice(16)を置く
                        if target_pos[0] == choice_pos[0]:
                            target_pos, choice_pos, exchange_num, exchange_operation = up(target_num, choice_num, exchange_num, exchange_operation)
                        else:
                            while target_pos[0]-1 != choice_pos[0]:
                                target_pos, choice_pos, exchange_num, exchange_operation = down(target_num, choice_num, exchange_num, exchange_operation)
                        #targetの左上にchoice(16)を置く
                        if target_pos[1] <= choice_pos[1]:
                            while target_pos[1]-1 != choice_pos[1]:
                                target_pos, choice_pos, exchange_num, exchange_operation = left(target_num, choice_num, exchange_num, exchange_operation)
                        else:
                            while target_pos[1]-1 != choice_pos[1]:
                                target_pos, choice_pos, exchange_num, exchange_operation = right(target_num, choice_num, exchange_num, exchange_operation)
                        
                        #targetをおきたい座標のx座標と同じになるまで移動
                        target_pos, choice_pos, exchange_num, exchange_operation = down(target_num, choice_num, exchange_num, exchange_operation)
                        target_pos, choice_pos, exchange_num, exchange_operation = right(target_num, choice_num, exchange_num, exchange_operation)
                        while target_pos[1] != pos[1]:
                            target_pos, choice_pos, exchange_num, exchange_operation = up(target_num, choice_num, exchange_num, exchange_operation)
                            target_pos, choice_pos, exchange_num, exchange_operation = left(target_num, choice_num, exchange_num, exchange_operation)
                            target_pos, choice_pos, exchange_num, exchange_operation = left(target_num, choice_num, exchange_num, exchange_operation)
                            target_pos, choice_pos, exchange_num, exchange_operation = down(target_num, choice_num, exchange_num, exchange_operation)
                            target_pos, choice_pos, exchange_num, exchange_operation = right(target_num, choice_num, exchange_num, exchange_operation)
                        #targetの上にchoiceを置く
                        target_pos, choice_pos, exchange_num, exchange_operation = up(target_num, choice_num, exchange_num, exchange_operation)
                        target_pos, choice_pos, exchange_num, exchange_operation = left(target_num, choice_num, exchange_num, exchange_operation)

                    #targetが最終的におきたいx座標よりも左
                    elif target_pos[1] < pos[1]:
                        #targetの上の座標にchoice(16)を置く
                        if target_pos[0] == choice_pos[0]:
                            target_pos, choice_pos, exchange_num, exchange_operation = up(target_num, choice_num, exchange_num, exchange_operation)
                        else:
                            while target_pos[0]-1 != choice_pos[0]:
                                target_pos, choice_pos, exchange_num, exchange_operation = down(target_num, choice_num, exchange_num, exchange_operation)
                        #targetの右上にchoice(16)を置く
                        if target_pos[1] >= choice_pos[1]:
                            while target_pos[1]+1 != choice_pos[1]:
                                target_pos, choice_pos, exchange_num, exchange_operation = right(target_num, choice_num, exchange_num, exchange_operation)
                        else:
                            while target_pos[1]+1 != choice_pos[1]:
                                target_pos, choice_pos, exchange_num, exchange_operation = left(target_num, choice_num, exchange_num, exchange_operation)

                        #targetを置きたい座標のx座標と同じになるまで移動
                        target_pos, choice_pos, exchange_num, exchange_operation = down(target_num, choice_num, exchange_num, exchange_operation)
                        target_pos, choice_pos, exchange_num, exchange_operation = left(target_num, choice_num, exchange_num, exchange_operation)
                        while target_pos[1] != pos[1]:
                            target_pos, choice_pos, exchange_num, exchange_operation = up(target_num, choice_num, exchange_num, exchange_operation)
                            target_pos, choice_pos, exchange_num, exchange_operation = right(target_num, choice_num, exchange_num, exchange_operation)
                            target_pos, choice_pos, exchange_num, exchange_operation = right(target_num, choice_num, exchange_num, exchange_operation)
                            target_pos, choice_pos, exchange_num, exchange_operation = down(target_num, choice_num, exchange_num, exchange_operation)
                            target_pos, choice_pos, exchange_num, exchange_operation = left(target_num, choice_num, exchange_num, exchange_operation)

                        #targetの上にchoic(16)を置く
                        target_pos, choice_pos, exchange_num, exchange_operation = up(target_num, choice_num, exchange_num, exchange_operation)
                        target_pos, choice_pos, exchange_num, exchange_operation = right(target_num, choice_num, exchange_num, exchange_operation)

                    #targetが最終的におきたいx座標と同じ
                    else:
                        #targetの上の座標にchoice(16)を置く
                        if target_pos[0] == choice_pos[0]:
                            target_pos, choice_pos, exchange_num, exchange_operation = up(target_num, choice_num, exchange_num, exchange_operation)
                        else:
                            while target_pos[0]-1 != choice_pos[0]:
                                target_pos, choice_pos, exchange_num, exchange_operation = down(target_num, choice_num, exchange_num, exchange_operation)

                        #targetの上にchoiceを置く
                        if target_pos[1] < choice_pos[1]:
                            while target_pos[1] != choice_pos[1]:
                                target_pos, choice_pos, exchange_num, exchange_operation = left(target_num, choice_num, exchange_num, exchange_operation)   
                        elif target_pos[1] > choice_pos[1]:
                            while target_pos[1] != choice_pos[1]:
                                target_pos, choice_pos, exchange_num, exchange_operation = right(target_num, choice_num, exchange_num, exchange_operation)   

                    #targetを置きたい座標のy座標になるまで移動
                    if target_pos[0] != pos[0]:
                        target_pos, choice_pos, exchange_num, exchange_operation = down(target_num, choice_num, exchange_num, exchange_operation)
                        while target_pos[0] != pos[0]:
                            target_pos, choice_pos, exchange_num, exchange_operation = right(target_num, choice_num, exchange_num, exchange_operation)
                            target_pos, choice_pos, exchange_num, exchange_operation = up(target_num, choice_num, exchange_num, exchange_operation)
                            target_pos, choice_pos, exchange_num, exchange_operation = up(target_num, choice_num, exchange_num, exchange_operation)
                            target_pos, choice_pos, exchange_num, exchange_operation = left(target_num, choice_num, exchange_num, exchange_operation)
                            target_pos, choice_pos, exchange_num, exchange_operation = down(target_num, choice_num, exchange_num, exchange_operation)
                
                #最終的に置きたい位置が右から2列目
                elif j == row - 2:
                    #targetが最終的におきたいx座標よりも左
                    if target_pos[1] < pos[1]+1:
                        #targetの上の座標にchoice(16)を置く
                        if target_pos[0] == choice_pos[0]:
                            target_pos, choice_pos, exchange_num, exchange_operation = up(target_num, choice_num, exchange_num, exchange_operation)
                        else:
                            while target_pos[0]-1 != choice_pos[0]:
                                target_pos, choice_pos, exchange_num, exchange_operation = down(target_num, choice_num, exchange_num, exchange_operation)
                        #targetの右上にchoice(16)を置く
                        if target_pos[1] >= choice_pos[1]:
                            while target_pos[1]+1 != choice_pos[1]:
                                target_pos, choice_pos, exchange_num, exchange_operation = right(target_num, choice_num, exchange_num, exchange_operation)
                        else:
                            while target_pos[1]+1 != choice_pos[1]:
                                target_pos, choice_pos, exchange_num, exchange_operation = left(target_num, choice_num, exchange_num, exchange_operation)

                        #targetを置きたい座標のx座標と同じになるまで移動
                        target_pos, choice_pos, exchange_num, exchange_operation = down(target_num, choice_num, exchange_num, exchange_operation)
                        target_pos, choice_pos, exchange_num, exchange_operation = left(target_num, choice_num, exchange_num, exchange_operation)
                        while target_pos[1] != pos[1]+1:
                            target_pos, choice_pos, exchange_num, exchange_operation = up(target_num, choice_num, exchange_num, exchange_operation)
                            target_pos, choice_pos, exchange_num, exchange_operation = right(target_num, choice_num, exchange_num, exchange_operation)
                            target_pos, choice_pos, exchange_num, exchange_operation = right(target_num, choice_num, exchange_num, exchange_operation)
                            target_pos, choice_pos, exchange_num, exchange_operation = down(target_num, choice_num, exchange_num, exchange_operation)
                            target_pos, choice_pos, exchange_num, exchange_operation = left(target_num, choice_num, exchange_num, exchange_operation)
                        target_pos, choice_pos, exchange_num, exchange_operation = up(target_num, choice_num, exchange_num, exchange_operation)
                        target_pos, choice_pos, exchange_num, exchange_operation = right(target_num, choice_num, exchange_num, exchange_operation)

                    #targetが最終的におきたいx座標の右と同じ
                    elif target_pos[1] == pos[1]+1:
                        #targetの上の座標にchoice(16)を置く
                        if target_pos[0] == choice_pos[0]:
                            target_pos, choice_pos, exchange_num, exchange_operation = up(target_num, choice_num, exchange_num, exchange_operation)
                        else:
                            while target_pos[0]-1 != choice_pos[0]:
                                target_pos, choice_pos, exchange_num, exchange_operation = down(target_num, choice_num, exchange_num, exchange_operation)
                        #targetの上にchoice(16)を移動
                        while target_pos[1] != choice_pos[1]:
                            target_pos, choice_pos, exchange_num, exchange_operation = right(target_num, choice_num, exchange_num, exchange_operation)

                    #targetを最終的に置きたいy座標まで移動
                    target_pos, choice_pos, exchange_num, exchange_operation = down(target_num, choice_num, exchange_num, exchange_operation)
                    while target_pos[0] != pos[0]:
                        target_pos, choice_pos, exchange_num, exchange_operation = left(target_num, choice_num, exchange_num, exchange_operation)
                        target_pos, choice_pos, exchange_num, exchange_operation = up(target_num, choice_num, exchange_num, exchange_operation)
                        target_pos, choice_pos, exchange_num, exchange_operation = up(target_num, choice_num, exchange_num, exchange_operation)
                        target_pos, choice_pos, exchange_num, exchange_operation = right(target_num, choice_num, exchange_num, exchange_operation)
                        target_pos, choice_pos, exchange_num, exchange_operation = down(target_num, choice_num, exchange_num, exchange_operation)


                #最終的に置きたい位置が右端
                elif j == row - 1:
                    #targetが最終的におきたいx座標よりも左
                    if target_pos[1] < pos[1]:
                        #targetの上の座標にchoice(16)を置く
                        if target_pos[0] == choice_pos[0]:
                            target_pos, choice_pos, exchange_num, exchange_operation = up(target_num, choice_num, exchange_num, exchange_operation)
                        else:
                            while target_pos[0]-1 != choice_pos[0]:
                                target_pos, choice_pos, exchange_num, exchange_operation = down(target_num, choice_num, exchange_num, exchange_operation)
                        #targetの右上にchoice(16)を置く
                        if target_pos[1] >= choice_pos[1]:
                            while target_pos[1]+1 != choice_pos[1]:
                                target_pos, choice_pos, exchange_num, exchange_operation = right(target_num, choice_num, exchange_num, exchange_operation)
                        else:
                            while target_pos[1]+1 != choice_pos[1]:
                                target_pos, choice_pos, exchange_num, exchange_operation = left(target_num, choice_num, exchange_num, exchange_operation)

                        #targetを置きたい座標のx座標と同じになるまで移動
                        target_pos, choice_pos, exchange_num, exchange_operation = down(target_num, choice_num, exchange_num, exchange_operation)
                        target_pos, choice_pos, exchange_num, exchange_operation = left(target_num, choice_num, exchange_num, exchange_operation)
                        while target_pos[1] != pos[1]:
                            target_pos, choice_pos, exchange_num, exchange_operation = up(target_num, choice_num, exchange_num, exchange_operation)
                            target_pos, choice_pos, exchange_num, exchange_operation = right(target_num, choice_num, exchange_num, exchange_operation)
                            target_pos, choice_pos, exchange_num, exchange_operation = right(target_num, choice_num, exchange_num, exchange_operation)
                            target_pos, choice_pos, exchange_num, exchange_operation = down(target_num, choice_num, exchange_num, exchange_operation)
                            target_pos, choice_pos, exchange_num, exchange_operation = left(target_num, choice_num, exchange_num, exchange_operation)
                        target_pos, choice_pos, exchange_num, exchange_operation = up(target_num, choice_num, exchange_num, exchange_operation)
                        target_pos, choice_pos, exchange_num, exchange_operation = right(target_num, choice_num, exchange_num, exchange_operation)

                    #targetが最終的におきたいx座標と同じ
                    elif target_pos[1] == pos[1]:
                        #targetの上の座標にchoice(16)を置く
                        if target_pos[0] == choice_pos[0]:
                            target_pos, choice_pos, exchange_num, exchange_operation = up(target_num, choice_num, exchange_num, exchange_operation)
                        else:
                            while target_pos[0]-1 != choice_pos[0]:
                                target_pos, choice_pos, exchange_num, exchange_operation = down(target_num, choice_num, exchange_num, exchange_operation)
                        #targetの上にchoice(16)を移動
                        while target_pos[1] != choice_pos[1]:
                            target_pos, choice_pos, exchange_num, exchange_operation = right(target_num, choice_num, exchange_num, exchange_operation)
                    
                    #targetを最終的に置きたいy座標まで移動
                    target_pos, choice_pos, exchange_num, exchange_operation = down(target_num, choice_num, exchange_num, exchange_operation)
                    while target_pos[0] != pos[0]+1:
                        target_pos, choice_pos, exchange_num, exchange_operation = left(target_num, choice_num, exchange_num, exchange_operation)
                        target_pos, choice_pos, exchange_num, exchange_operation = up(target_num, choice_num, exchange_num, exchange_operation)
                        target_pos, choice_pos, exchange_num, exchange_operation = up(target_num, choice_num, exchange_num, exchange_operation)
                        target_pos, choice_pos, exchange_num, exchange_operation = right(target_num, choice_num, exchange_num, exchange_operation)
                        target_pos, choice_pos, exchange_num, exchange_operation = down(target_num, choice_num, exchange_num, exchange_operation)
                    
                    #3,4を最終的におきたい座標となるよう移動
                    target_pos, choice_pos, exchange_num, exchange_operation = left(target_num, choice_num, exchange_num, exchange_operation)
                    target_pos, choice_pos, exchange_num, exchange_operation = up(target_num, choice_num, exchange_num, exchange_operation)
                    target_pos, choice_pos, exchange_num, exchange_operation = up(target_num, choice_num, exchange_num, exchange_operation)
                    target_pos, choice_pos, exchange_num, exchange_operation = right(target_num, choice_num, exchange_num, exchange_operation)
                    target_pos, choice_pos, exchange_num, exchange_operation = down(target_num, choice_num, exchange_num, exchange_operation)

            print("交換回数：" + str(exchange_num))    

            print(split_list)
            print()
            print("       ↓")
            print()
        

    #さいごの2行（たいち）
    
    print("ライン1選択画像位置：" + str(selection_image_position[0]) + str(selection_image_position[1]))
    print("ライン1交換回数" + str(exchange_num))
    print("ライン1交換操作：" + exchange_operation)

    f = open('answer.txt', 'w')
    f.write('2\n') 
    f.write(str(selection_image_position[0]) + str(selection_image_position[1]) + '\n')
    f.write(str(exchange_num) + '\n')
    f.write(exchange_operation + '\n')

    return exchange_num



#メイン
#ファイルオープン
# f = open('画像問題フォーマット.txt', 'r', encoding='UTF-8')
# data = f.readlines()
# f.close()

# s0 = data[0].rstrip('\n').rstrip(',')
# s1 = data[1].rstrip('\n').rstrip(',')
# s2 = data[2].rstrip('\n').rstrip(',')
# s3 = data[3].rstrip('\n').rstrip(',')
# s4 = data[4].rstrip('\n').rstrip(',')

# l0 = [int(x.strip()) for x in s0.split(',')]
# l1 = [int(x.strip()) for x in s1.split(',')]
# l2 = [int(x.strip()) for x in s2.split(',')]
# l3 = [int(x.strip()) for x in s3.split(',')]
# l4 = [int(x.strip()) for x in s4.split(',')]

# split_list = np.array([l1, l2, l3, l4])
# print(l0)


random_num = random.sample(range(1, 17), 16)
random_list = np.array(random_num)
split_list = random_list.reshape(4, 4)

copy_list = copy.copy(split_list)

print(split_list)
print()
print("       ↓")
print()

exchange_num = 0
exchange_num = move(split_list, exchange_num)
print("交換回数：" + str(exchange_num))
print(split_list)

[[ 7 12  4  5]
 [14  9 13  8]
 [ 6  2 11 16]
 [10  1  3 15]]

       ↓

target_num = 1----------------------------------------------------------
交換回数：18
[[ 1  7  4  5]
 [16 12 13  8]
 [ 9 14  2 11]
 [ 6 10  3 15]]

       ↓

target_num = 2----------------------------------------------------------
交換回数：31
[[ 1  2  7  5]
 [12 16  4  8]
 [ 9 13 14 11]
 [ 6 10  3 15]]

       ↓

target_num = 3----------------------------------------------------------
交換回数：49
[[ 1  2  5  3]
 [12 13  7 16]
 [ 9 14  8  4]
 [ 6 10 15 11]]

       ↓

target_num = 4----------------------------------------------------------
交換回数：56
[[ 1  2  3  4]
 [12 13 16  5]
 [ 9 14  7  8]
 [ 6 10 15 11]]

       ↓

target_num = 5----------------------------------------------------------
交換回数：69
[[ 1  2  3  4]
 [ 5 16 14  8]
 [12  9 13  7]
 [ 6 10 15 11]]

       ↓

target_num = 6----------------------------------------------------------
交換回数：80
[[ 1  2  3  4]
 [ 5  6  9  8]
 [10 16 14  7]
 [12 15 13 11]]

       ↓

target_num

In [2]:
#エラー用コード


#上下左右に移動する関数
def up(target_num, choice_num, exchange):
    target_pos = tuple(nd[0] for nd in np.where(split_list == target_num))
    choice_pos = tuple(nd[0] for nd in np.where(split_list == choice_num))

    np.put(split_list, [4 * choice_pos[0] + choice_pos[1]], split_list[choice_pos[0]-1][choice_pos[1]])
    np.put(split_list, [4 * choice_pos[0] + choice_pos[1] - 4], choice_num)
    
    target_pos = tuple(nd[0] for nd in np.where(split_list == target_num))
    choice_pos = tuple(nd[0] for nd in np.where(split_list == choice_num))
    exchange += 1
    print(split_list)
    print("")
    return target_pos, choice_pos, exchange

def down(target_num, choice_num, exchange):
    target_pos = tuple(nd[0] for nd in np.where(split_list == target_num))
    choice_pos = tuple(nd[0] for nd in np.where(split_list == choice_num))

    np.put(split_list, [4 * (choice_pos[0]) + choice_pos[1]], split_list[choice_pos[0]+1][choice_pos[1]])
    np.put(split_list, [4 * (choice_pos[0]) + choice_pos[1] + 4], choice_num)
    
    target_pos = tuple(nd[0] for nd in np.where(split_list == target_num))
    choice_pos = tuple(nd[0] for nd in np.where(split_list == choice_num))
    print(split_list)
    print("")
    return target_pos, choice_pos, exchange

def right(target_num, choice_num, exchange):
    target_pos = tuple(nd[0] for nd in np.where(split_list == target_num))
    choice_pos = tuple(nd[0] for nd in np.where(split_list == choice_num))

    np.put(split_list, [4 * (choice_pos[0]) + choice_pos[1]], split_list[choice_pos[0]][choice_pos[1]+1])
    np.put(split_list, [4 * (choice_pos[0]) + choice_pos[1] + 1], choice_num)
    
    target_pos = tuple(nd[0] for nd in np.where(split_list == target_num))
    choice_pos = tuple(nd[0] for nd in np.where(split_list == choice_num))
    exchange += 1
    print(split_list)
    print("")
    return target_pos, choice_pos, exchange

def left(target_num, choice_num, exchange):
    target_pos = tuple(nd[0] for nd in np.where(split_list == target_num))
    choice_pos = tuple(nd[0] for nd in np.where(split_list == choice_num))

    np.put(split_list, [4 * (choice_pos[0]) + choice_pos[1]], split_list[choice_pos[0]][choice_pos[1]-1])
    np.put(split_list, [4 * (choice_pos[0]) + choice_pos[1] -1], choice_num)
    
    target_pos = tuple(nd[0] for nd in np.where(split_list == target_num))
    choice_pos = tuple(nd[0] for nd in np.where(split_list == choice_num))
    exchange += 1
    print(split_list)
    print("")
    return target_pos, choice_pos, exchange


def move(split_list, exchange):
    columns = split_list.shape[0]
    row = split_list.shape[1]

    #最後2行を除いて並び替え（たくと）
    for i in range(columns - 2):
        for j in range(row):
            target_num = i * row + j + 1
            choice_num = columns * row

            target_pos = tuple(nd[0] for nd in np.where(split_list == target_num))
            choice_pos = tuple(nd[0] for nd in np.where(split_list == choice_num))

            print("target_num = " + str(target_num) + "----------------------------------------------------------")

            #最終的に置きたい座標
            if target_num % row == 0: pos = (target_num // row - 1, row - 1)
            else: pos = (target_num // row, target_num % row - 1)

            #targetが下端でない
            if target_pos[0] != columns-1:
                #右2列を除いた列を並び替え
                if j != row - 1 and j != row - 2:
                    #targetが最終的に置きたいx座標よりも右
                    if target_pos[1] > pos[1]:
                        #targetの左下にchoice(16)を置く
                        if target_pos[1] <= choice_pos[1]:
                            while target_pos[1]-1 != choice_pos[1]:
                                target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                        else:
                            while target_pos[1]-1 != choice_pos[1]:
                                target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                        #targetを最終的に置きたいy座標に移動
                        if target_pos[0] < choice_pos[0]:
                            while target_pos[0]+1 != choice_pos[0]:
                                target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                        else:
                            while target_pos[0]+1 != choice_pos[0]:
                                target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)

                        #targetを置きたい座標のx座標と同じになるまで移動
                        if target_pos[1] != pos[1]:
                            target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                            while target_pos[1] != pos[1]:
                                target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                                target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                                target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                                target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                                target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                    
                    #targetを最終的に置きたいx座標よりも左
                    elif target_pos[1] < pos[1]:
                        #targetの右下にchoice(16)を置く
                        if target_pos[1] >= choice_pos[1]:
                            while target_pos[1]+1 != choice_pos[1]:
                                target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                        else:
                            while target_pos[1]+1 != choice_pos[1]:
                                target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                        while target_pos[0]+1 != choice_pos[0]:
                            target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                        #targetを置きたい座標のx座標と同じになるまで移動
                        if target_pos[1] != pos[1]:
                            target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                            while target_pos[1] != pos[1]:
                                target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                                target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                                target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                                target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                                target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                            #targetの右にchoice(16)をおく
                            target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                        
                    
                    #targetが最終的に置きたいx座標と同じ
                    elif target_pos[1] == pos[1]:
                        #targetの右にchoice(16)をおく
                        #targetよりchoiceが右
                        if target_pos[1] < choice_pos[1]:
                            while target_pos[1]+1 != choice_pos[1]:
                                target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                            #targetよりchoiceが上
                            if target_pos[0] > choice_pos[0]:
                                while target_pos[0] != choice_pos[0]:
                                    target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                            #targetよりchoiceが下
                            else:
                                while target_pos[0] != choice_pos[0]:
                                    target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)

                        #targetよりchoiceが左
                        elif target_pos[1] > choice_pos[1]:
                            #targetがchoiceより上or下
                            if target_pos[0] != choice_pos[0]:
                                while target_pos[1]+1 != choice_pos[1]:
                                    target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                                #targetよりchoiceが上
                                if target_pos[0] > choice_pos[0]:
                                    while target_pos[0] != choice_pos[0]:
                                        target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                                #targetよりchoiceが下
                                else:
                                    while target_pos[0] != choice_pos[0]:
                                        target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                            #targetがchoiceと同じx座標
                            else:
                                target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                                while target_pos[1]+1 != choice_pos[1]:
                                    target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                                target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                        
                        #targetとchoiceのx座標が同じ
                        else:
                            target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                            #targetよりchoiceが上
                            if target_pos[0] > choice_pos[0]:
                                while target_pos[0] != choice_pos[0]:
                                    target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                            #targetよりchoiceが下
                            else:
                                while target_pos[0] != choice_pos[0]:
                                    target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)

                         
                    #targetを置きたい座標のy座標と同じになるまで移動
                    if target_pos[0] != pos[0]:
                        target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                        while target_pos[0] != pos[0]:
                            target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                
                #最終的に置きたい位置が右から2列目
                elif j == row - 2:
                    #最終的に置きたい座標にある
                    if target_pos[0] == pos[0] and target_pos[1] == pos[1]:
                        while target_pos[1]+1 != choice_pos[1]:
                            target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                        while target_pos[0] != choice_pos[0]:
                            target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)

                    #最終的に置きたいy座標でない
                    elif target_pos[0] != pos[0]:
                        #最終的におきたいx座標でない
                        if target_pos[1] != pos[1]+1:
                            #targetよりも下にchoiceがある
                            if target_pos[0] < choice_pos[0]:
                                while target_pos[0]+1 != choice_pos[0]:
                                    target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                            #targetよりも上にchoiceがある
                            elif target_pos[0] > choice_pos[0]:
                                while target_pos[0]+1 != choice_pos[0]:
                                    target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)

                            #targetの右にchoiceを移動
                            #targetよりも右にchoiceがある
                            if target_pos[1] < choice_pos[1]:
                                while target_pos[1]+1 != choice_pos[1]:
                                    target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                            #targetよりも左にchoiceがある
                            else:
                                while target_pos[1]+1 != choice_pos[1]:
                                    target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                            
                            
                            #targetを右端まで移動
                            target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                            while target_pos[1] != pos[1]+1:
                                target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                                target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                                target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                                target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                                target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                            #targetを最終的に置きたいy座標まで移動
                            target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                            while target_pos[0] != pos[0]:
                                target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                                target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                                target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                                target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                                target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)

                        #最終的におきたいx座標にある
                        elif target_pos[1] == pos[1]+1: 
                            #targetのx座標の左にchoiceを移動
                            if target_pos[1] == choice_pos[1]:
                                target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                            else:
                                while target_pos[1]-1 != choice_pos[1]:
                                    target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)

                            #targetの左上に移動
                            #targetよりも下にchoiceがある
                            if target_pos[0] <= choice_pos[0]:
                                while target_pos[0]-1 != choice_pos[0]:
                                    target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                            #targetよりも上にchoiceがある
                            else:
                                while target_pos[0]-1 != choice_pos[0]:
                                    target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)

                            #targetを最終的に置きたいy座標まで移動
                            target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                            while target_pos[0] != pos[0]:
                                target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                                target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                                target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                                target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                                target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)


                #最終的に置きたい位置が右端
                elif j == row - 1:

                    #逆順に並んでいる
                    if target_pos[0] == pos[0] and target_pos[1] == pos[1]-1:
                        target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)

                    #targetがtarget-1の下
                    elif target_pos[0] == pos[0]+1 and target_pos[1] == pos[1]:
                        #targetの左にchoice
                        #targetの左の座標に移動
                        if target_pos[1] > choice_pos[1]:
                            while target_pos[1]-1 != choice_pos[1]:
                                target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                        else:
                            while target_pos[1]-1 != choice_pos[1]:
                                target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                        #targetの左上に移動
                        if target_pos[0] < choice_pos[0]:
                            while target_pos[0]-1 != choice_pos[0]:
                                target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                        
                        #3,4を最終的に置きたい座標となるよう移動
                        target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)

                    elif target_pos[0] != pos[0]+1 or target_pos[1] != pos[1]:
                        #targetの上にchoiceがある
                        if target_pos[0] > choice_pos[0]:
                            while target_pos[0]+1 != choice_pos[0]:
                                target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                        #targetの下にchoiceがある
                        else:
                            while target_pos[0]+1 != choice_pos[0]:
                                target_pos, choice_pos, exchange = up(target_num, choice_num, exchange) 

                        #targetの右にchoiceがある
                        if target_pos[1] < choice_pos[1]:
                            while target_pos[1] != choice_pos[1]:
                                target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                        #targetの左にchoiceがある
                        elif target_pos[1] > choice_pos[1]:
                            while target_pos[1] != choice_pos[1]:
                                target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)

                        

                        #targetを右端まで移動
                        if target_pos[1] != pos[1]:
                            target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                        else:
                            target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                        while target_pos[1] != pos[1]:
                            target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)

                        #targetをtarget-1の下に移動
                        if target_pos[0] != pos[0]+1:
                            while target_pos[0] != pos[0]+1:
                                target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                                target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                                target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                                target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                                target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)

                        #3,4を最終的に置きたい座標となるよう移動
                        target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)                 


            #targetが下端
            else:
                #右2列を除いた列を並び替え
                if j != row - 1 and j != row - 2:
                    #targetが最終的におきたいx座標よりも右
                    if target_pos[1] > pos[1]:
                        #targetの上の座標にchoice(16)を置く
                        if target_pos[0] == choice_pos[0]:
                            target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                        else:
                            while target_pos[0]-1 != choice_pos[0]:
                                target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                        #targetの左上にchoice(16)を置く
                        if target_pos[1] <= choice_pos[1]:
                            while target_pos[1]-1 != choice_pos[1]:
                                target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                        else:
                            while target_pos[1]-1 != choice_pos[1]:
                                target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                        
                        #targetをおきたい座標のx座標と同じになるまで移動
                        target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                        while target_pos[1] != pos[1]:
                            target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                        #targetの上にchoiceを置く
                        target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)

                    #targetが最終的におきたいx座標よりも左
                    elif target_pos[1] < pos[1]:
                        #targetの上の座標にchoice(16)を置く
                        if target_pos[0] == choice_pos[0]:
                            target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                        else:
                            while target_pos[0]-1 != choice_pos[0]:
                                target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                        #targetの右上にchoice(16)を置く
                        if target_pos[1] >= choice_pos[1]:
                            while target_pos[1]+1 != choice_pos[1]:
                                target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                        else:
                            while target_pos[1]+1 != choice_pos[1]:
                                target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)

                        #targetを置きたい座標のx座標と同じになるまで移動
                        target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                        while target_pos[1] != pos[1]:
                            target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)

                        #targetの上にchoic(16)を置く
                        target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)

                    #targetが最終的におきたいx座標と同じ
                    else:
                        #targetの上の座標にchoice(16)を置く
                        if target_pos[0] == choice_pos[0]:
                            target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                        else:
                            while target_pos[0]-1 != choice_pos[0]:
                                target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)

                        #targetの上にchoiceを置く
                        if target_pos[1] < choice_pos[1]:
                            while target_pos[1] != choice_pos[1]:
                                target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)   
                        elif target_pos[1] > choice_pos[1]:
                            while target_pos[1] != choice_pos[1]:
                                target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)   

                    #targetを置きたい座標のy座標になるまで移動
                    if target_pos[0] != pos[0]:
                        target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                        while target_pos[0] != pos[0]:
                            target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                
                #最終的に置きたい位置が右から2列目
                elif j == row - 2:
                    #targetが最終的におきたいx座標よりも左
                    if target_pos[1] < pos[1]+1:
                        #targetの上の座標にchoice(16)を置く
                        if target_pos[0] == choice_pos[0]:
                            target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                        else:
                            while target_pos[0]-1 != choice_pos[0]:
                                target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                        #targetの右上にchoice(16)を置く
                        if target_pos[1] >= choice_pos[1]:
                            while target_pos[1]+1 != choice_pos[1]:
                                target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                        else:
                            while target_pos[1]+1 != choice_pos[1]:
                                target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)

                        #targetを置きたい座標のx座標と同じになるまで移動
                        target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                        while target_pos[1] != pos[1]+1:
                            target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)

                    #targetが最終的におきたいx座標の右と同じ
                    elif target_pos[1] == pos[1]+1:
                        #targetの上の座標にchoice(16)を置く
                        if target_pos[0] == choice_pos[0]:
                            target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                        else:
                            while target_pos[0]-1 != choice_pos[0]:
                                target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                        #targetの上にchoice(16)を移動
                        while target_pos[1] != choice_pos[1]:
                            target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)

                    #targetを最終的に置きたいy座標まで移動
                    target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                    while target_pos[0] != pos[0]:
                        target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)


                #最終的に置きたい位置が右端
                elif j == row - 1:
                    #targetが最終的におきたいx座標よりも左
                    if target_pos[1] < pos[1]:
                        #targetの上の座標にchoice(16)を置く
                        if target_pos[0] == choice_pos[0]:
                            target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                        else:
                            while target_pos[0]-1 != choice_pos[0]:
                                target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                        #targetの右上にchoice(16)を置く
                        if target_pos[1] >= choice_pos[1]:
                            while target_pos[1]+1 != choice_pos[1]:
                                target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                        else:
                            while target_pos[1]+1 != choice_pos[1]:
                                target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)

                        #targetを置きたい座標のx座標と同じになるまで移動
                        target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                        while target_pos[1] != pos[1]:
                            target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)

                    #targetが最終的におきたいx座標と同じ
                    elif target_pos[1] == pos[1]:
                        #targetの上の座標にchoice(16)を置く
                        if target_pos[0] == choice_pos[0]:
                            target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                        else:
                            while target_pos[0]-1 != choice_pos[0]:
                                target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                        #targetの上にchoice(16)を移動
                        while target_pos[1] != choice_pos[1]:
                            target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                    
                    #targetを最終的に置きたいy座標まで移動
                    target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                    while target_pos[0] != pos[0]+1:
                        target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                    
                    #3,4を最終的におきたい座標となるよう移動
                    target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                    target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                    target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                    target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                    target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)

            print("交換回数：" + str(exchange))    

            print(split_list)
            print()
            print("       ↓")
            print()
            

    #さいごの2行（たいち）
    

    return exchange


split_list = copy.copy(copy_list)

print(split_list)
print()
print("       ↓")
print()

exchange = 0

exchange = move(split_list, exchange)
print("交換回数：" + str(exchange))
print(split_list)

[[ 5  4  8  2]
 [13  9  6  7]
 [ 1  3 14 11]
 [10 16 12 15]]

       ↓

target_num = 1----------------------------------------------------------
[[ 5  4  8  2]
 [13  9  6  7]
 [ 1 16 14 11]
 [10  3 12 15]]

[[ 5  4  8  2]
 [13 16  6  7]
 [ 1  9 14 11]
 [10  3 12 15]]

[[ 5  4  8  2]
 [16 13  6  7]
 [ 1  9 14 11]
 [10  3 12 15]]

[[ 5  4  8  2]
 [ 1 13  6  7]
 [16  9 14 11]
 [10  3 12 15]]

[[ 5  4  8  2]
 [ 1 13  6  7]
 [ 9 16 14 11]
 [10  3 12 15]]

[[ 5  4  8  2]
 [ 1 16  6  7]
 [ 9 13 14 11]
 [10  3 12 15]]

[[ 5 16  8  2]
 [ 1  4  6  7]
 [ 9 13 14 11]
 [10  3 12 15]]

[[16  5  8  2]
 [ 1  4  6  7]
 [ 9 13 14 11]
 [10  3 12 15]]

[[ 1  5  8  2]
 [16  4  6  7]
 [ 9 13 14 11]
 [10  3 12 15]]

交換回数：7
[[ 1  5  8  2]
 [16  4  6  7]
 [ 9 13 14 11]
 [10  3 12 15]]

       ↓

target_num = 2----------------------------------------------------------
[[ 1  5  8  2]
 [ 4 16  6  7]
 [ 9 13 14 11]
 [10  3 12 15]]

[[ 1  5  8  2]
 [ 4  6 16  7]
 [ 9 13 14 11]
 [10  3 12 15]]

[[ 1  5 16  2]
 [ 4  