In [1]:
import numpy as np

In [2]:
#上下左右に移動する関数
def up(target_num, choice_num, exchange):
    target_pos = tuple(nd[0] for nd in np.where(split_list == target_num))
    choice_pos = tuple(nd[0] for nd in np.where(split_list == choice_num))

    np.put(split_list, [4 * choice_pos[0] + choice_pos[1]], split_list[choice_pos[0]-1][choice_pos[1]])
    np.put(split_list, [4 * choice_pos[0] + choice_pos[1] - 4], choice_num)
    
    target_pos = tuple(nd[0] for nd in np.where(split_list == target_num))
    choice_pos = tuple(nd[0] for nd in np.where(split_list == choice_num))
    exchange += 1
    print(split_list)
    print("")
    return target_pos, choice_pos, exchange

def down(target_num, choice_num, exchange):
    target_pos = tuple(nd[0] for nd in np.where(split_list == target_num))
    choice_pos = tuple(nd[0] for nd in np.where(split_list == choice_num))

    np.put(split_list, [4 * (choice_pos[0]) + choice_pos[1]], split_list[choice_pos[0]+1][choice_pos[1]])
    np.put(split_list, [4 * (choice_pos[0]) + choice_pos[1] + 4], choice_num)
    
    target_pos = tuple(nd[0] for nd in np.where(split_list == target_num))
    choice_pos = tuple(nd[0] for nd in np.where(split_list == choice_num))
    exchange += 1
    print(split_list)
    print("")
    return target_pos, choice_pos, exchange

def right(target_num, choice_num, exchange):
    target_pos = tuple(nd[0] for nd in np.where(split_list == target_num))
    choice_pos = tuple(nd[0] for nd in np.where(split_list == choice_num))

    np.put(split_list, [4 * (choice_pos[0]) + choice_pos[1]], split_list[choice_pos[0]][choice_pos[1]+1])
    np.put(split_list, [4 * (choice_pos[0]) + choice_pos[1] + 1], choice_num)
    
    target_pos = tuple(nd[0] for nd in np.where(split_list == target_num))
    choice_pos = tuple(nd[0] for nd in np.where(split_list == choice_num))
    exchange += 1
    print(split_list)
    print("")
    return target_pos, choice_pos, exchange

def left(target_num, choice_num, exchange):
    target_pos = tuple(nd[0] for nd in np.where(split_list == target_num))
    choice_pos = tuple(nd[0] for nd in np.where(split_list == choice_num))

    np.put(split_list, [4 * (choice_pos[0]) + choice_pos[1]], split_list[choice_pos[0]][choice_pos[1]-1])
    np.put(split_list, [4 * (choice_pos[0]) + choice_pos[1] -1], choice_num)
    
    target_pos = tuple(nd[0] for nd in np.where(split_list == target_num))
    choice_pos = tuple(nd[0] for nd in np.where(split_list == choice_num))
    exchange += 1
    print(split_list)
    print("")
    return target_pos, choice_pos, exchange

In [3]:
#ファイルオープン
f = open('画像問題フォーマット.txt', 'r', encoding='UTF-8')
data = f.readlines()
f.close()

s0 = data[0].rstrip('\n').rstrip(',')
s1 = data[1].rstrip('\n').rstrip(',')
s2 = data[2].rstrip('\n').rstrip(',')
s3 = data[3].rstrip('\n').rstrip(',')
s4 = data[4].rstrip('\n').rstrip(',')

l0 = [int(x.strip()) for x in s0.split(',')]
l1 = [int(x.strip()) for x in s1.split(',')]
l2 = [int(x.strip()) for x in s2.split(',')]
l3 = [int(x.strip()) for x in s3.split(',')]
l4 = [int(x.strip()) for x in s4.split(',')]

split_list = np.array([l1, l2, l3, l4])

print(l0)
print(split_list)

[4, 4, 2, 100, 20]
[[ 7 12  2  5]
 [11 16  6  1]
 [10  4  9 15]
 [13 14  3  8]]


In [7]:
# split_list = np.array([[14, 12, 8, 11],
#                        [4, 2, 3, 6],
#                        [7, 13, 9, 5],
#                        [16, 15, 1, 10]])
print(split_list)
print()
print("       ↓")
print()

exchange = 0

def move(split_list, exchange):
    columns = split_list.shape[0]
    row = split_list.shape[1]

    #最後2行を除いて並び替え（たくと）
    for i in range(columns - 2):
        for j in range(row):
            target_num = i * row + j + 1
            choice_num = columns * row

            target_pos = tuple(nd[0] for nd in np.where(split_list == target_num))
            choice_pos = tuple(nd[0] for nd in np.where(split_list == choice_num))

            print("target_num = " + str(target_num) + "----------------------------------------------------------")

            #最終的に置きたい座標
            if target_num % row == 0: pos = (target_num // row - 1, row - 1)
            else: pos = (target_num // row, target_num % row - 1)

            #targetが下端でない
            if target_pos[0] != columns-1:
                #右2列を除いた列を並び替え
                if j != row - 1 and j != row - 2:
                    #targetが最終的に置きたいx座標よりも右
                    if target_pos[1] > pos[1]:
                        #targetの左下にchoice(16)を置く
                        if target_pos[1] <= choice_pos[1]:
                            while target_pos[1]-1 != choice_pos[1]:
                                target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                        else:
                            while target_pos[1]-1 != choice_pos[1]:
                                target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                        #targetを最終的に置きたいy座標に移動
                        if target_pos[0] < choice_pos[0]:
                            while target_pos[0]+1 != choice_pos[0]:
                                target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                        else:
                            while target_pos[0]+1 != choice_pos[0]:
                                target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)

                        #targetを置きたい座標のx座標と同じになるまで移動
                        if target_pos[1] != pos[1]:
                            target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                            while target_pos[1] != pos[1]:
                                target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                                target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                                target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                                target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                                target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                    
                    #targetを最終的に置きたいx座標よりも左
                    elif target_pos[1] < pos[1]:
                        #targetの右下にchoice(16)を置く
                        if target_pos[1] >= choice_pos[1]:
                            while target_pos[1]+1 != choice_pos[1]:
                                target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                        else:
                            while target_pos[1]+1 != choice_pos[1]:
                                target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                        while target_pos[0]+1 != choice_pos[0]:
                            target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                        #targetを置きたい座標のx座標と同じになるまで移動
                        if target_pos[1] != pos[1]:
                            target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                            while target_pos[1] != pos[1]:
                                target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                                target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                                target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                                target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                                target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                            #targetの右にchoice(16)をおく
                            target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                        
                    
                    #targetが最終的に置きたいx座標と同じ
                    elif target_pos[1] == pos[1]:
                        #targetの右にchoice(16)をおく
                        #targetよりchoiceが右
                        if target_pos[1] < choice_pos[1]:
                            while target_pos[1]+1 != choice_pos[1]:
                                target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                            #targetよりchoiceが上
                            if target_pos[0] > choice_pos[0]:
                                while target_pos[0] != choice_pos[0]:
                                    target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                            #targetよりchoiceが下
                            else:
                                while target_pos[0] != choice_pos[0]:
                                    target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)

                        #targetよりchoiceが左
                        elif target_pos[1] > choice_pos[1]:
                            #targetがchoiceより上or下
                            if target_pos[0] != choice_pos[0]:
                                while target_pos[1]+1 != choice_pos[1]:
                                    target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                                #targetよりchoiceが上
                                if target_pos[0] > choice_pos[0]:
                                    while target_pos[0] != choice_pos[0]:
                                        target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                                #targetよりchoiceが下
                                else:
                                    while target_pos[0] != choice_pos[0]:
                                        target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                            #targetがchoiceと同じx座標
                            else:
                                target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                                while target_pos[1]+1 != choice_pos[1]:
                                    target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                                target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                        
                        #targetとchoiceのx座標が同じ
                        else:
                            target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                            #targetよりchoiceが上
                            if target_pos[0] > choice_pos[0]:
                                while target_pos[0] != choice_pos[0]:
                                    target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                            #targetよりchoiceが下
                            else:
                                while target_pos[0] != choice_pos[0]:
                                    target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)

                         
                    #targetを置きたい座標のy座標と同じになるまで移動
                    if target_pos[0] != pos[0]:
                        target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                        while target_pos[0] != pos[0]:
                            target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                
                #最終的に置きたい位置が右から2列目
                elif j == row - 2:
                    #最終的に置きたい座標にある
                    if target_pos[0] == pos[0] and target_pos[1] == pos[1]:
                        while target_pos[1]+1 != choice_pos[1]:
                            target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                        while target_pos[0] != choice_pos[0]:
                            target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)

                    #最終的に置きたいy座標でない
                    elif target_pos[0] != pos[0]:
                        #最終的におきたいx座標でない
                        if target_pos[1] != pos[1]+1:
                            #targetよりも右にchoiceがある
                            if target_pos[1] < choice_pos[1]:
                                while target_pos[1]+1 != choice_pos[1]:
                                    target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                            #targetよりも左にchoiceがある
                            else:
                                while target_pos[1]+1 != choice_pos[1]:
                                    target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                            
                            #targetの右にchoiceを移動
                            #targetよりも下にchoiceがある
                            if target_pos[0] < choice_pos[0]:
                                while target_pos[0] != choice_pos[0]:
                                    target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                            #targetよりも上にchoiceがある
                            else:
                                while target_pos[0] != choice_pos[0]:
                                    target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                            
                            #targetを右端まで移動
                            target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                            while target_pos[1] != pos[1]+1:
                                target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                                target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                                target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                                target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                                target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                            #targetを最終的に置きたいy座標まで移動
                            target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                            while target_pos[0] != pos[0]:
                                target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                                target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                                target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                                target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                                target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)

                        #最終的におきたいx座標にある
                        elif target_pos[1] == pos[1]+1: 
                            #targetのx座標の左にchoiceを移動
                            if target_pos[1] == choice_pos[1]:
                                target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                            else:
                                while target_pos[1]-1 != choice_pos[1]:
                                    target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)

                            #targetの左上に移動
                            #targetよりも下にchoiceがある
                            if target_pos[0] < choice_pos[0]:
                                while target_pos[0]-1 != choice_pos[0]:
                                    target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                            #targetよりも上にchoiceがある
                            else:
                                while target_pos[0]-1 != choice_pos[0]:
                                    target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)

                            #targetを最終的に置きたいy座標まで移動
                            target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                            while target_pos[0] != pos[0]:
                                target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                                target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                                target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                                target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                                target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)


                #最終的に置きたい位置が右端
                elif j == row - 1:
                    #逆順に並んでいる
                    if target_pos[0] == pos[0] and target_pos[1] == pos[1]-1:
                        target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)

                    #targetがtarget-1の下
                    elif target_pos[0] == pos[0]+1 and target_pos[1] == pos[1]:
                        #targetの左にchoice
                        #targetの左の座標に移動
                        if target_pos[1] > choice_pos[1]:
                            while target_pos[1]-1 != choice_pos[1]:
                                target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                        else:
                            while target_pos[1]-1 != choice_pos[1]:
                                target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                        #targetの左に移動
                        if target_pos[0] < choice_pos[0]:
                            while target_pos[0]-1 != choice_pos[0]:
                                target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                        
                        #3,4を最終的に置きたい座標となるよう移動
                        target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)

                    elif target_pos[0] != pos[0]+1 or target_pos[1] != pos[1]:
                        #targetの右にchoiceがある
                        if target_pos[1] < choice_pos[1]:
                            while target_pos[1]+1 != choice_pos[1]:
                                target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                        #targetの左にchoiceがある
                        else:
                            while target_pos[1]+1 != choice_pos[1]:
                                target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)

                        #targetの上にchoiceがある
                        if target_pos[0] > choice_pos[0]:
                            while target_pos[0] != choice_pos[0]:
                                target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                        #targetの下にchoiceがある
                        else:
                            while target_pos[0] != choice_pos[0]:
                                target_pos, choice_pos, exchange = up(target_num, choice_num, exchange) 

                        #targetを右端まで移動
                        target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                        while target_pos[1] != pos[1]:
                            target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)

                        #targetをtarget-1の下に移動
                        if target_pos[0] != pos[0]+1:
                            target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                        while target_pos[0] != pos[0]+1:
                            target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)

                        #3,4を最終的に置きたい座標となるよう移動
                        target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)                 


            #targetが下端
            else:
                #右2列を除いた列を並び替え
                if j != row - 1 and j != row - 2:
                    #targetが最終的におきたいx座標よりも右
                    if target_pos[1] > pos[1]:
                        #targetの上の座標にchoice(16)を置く
                        if target_pos[0] == choice_pos[0]:
                            target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                        else:
                            while target_pos[0]-1 != choice_pos[0]:
                                target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                        #targetの左上にchoice(16)を置く
                        if target_pos[1] <= choice_pos[1]:
                            while target_pos[1]-1 != choice_pos[1]:
                                target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                        else:
                            while target_pos[1]-1 != choice_pos[1]:
                                target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                        
                        #targetをおきたい座標のx座標と同じになるまで移動
                        target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                        while target_pos[1] != pos[1]:
                            target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)

                    #targetが最終的におきたいx座標よりも左or同じ
                    elif target_pos[1] <= pos[1]:
                        #targetの上の座標にchoice(16)を置く
                        if target_pos[0] == choice_pos[0]:
                            target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                        else:
                            while target_pos[0]-1 != choice_pos[0]:
                                target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                        #targetの右上にchoice(16)を置く
                        if target_pos[1] >= choice_pos[1]:
                            while target_pos[1]+1 != choice_pos[1]:
                                target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                        else:
                            while target_pos[1]+1 != choice_pos[1]:
                                target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)

                        #targetを置きたい座標のx座標と同じになるまで移動
                        target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                        while target_pos[1] != pos[1]:
                            target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)

                        #targetの右にchoic(16)を置く
                        target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)

                    #targetを置きたい座標のy座標になるまで移動
                    if target_pos[0] != pos[0]:
                        target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                        while target_pos[0] != pos[0]:
                            target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                
                #最終的に置きたい位置が右から2列目
                elif j == row - 2:
                    #targetが最終的におきたいx座標よりも左
                    if target_pos[1] < pos[1]+1:
                        #targetの上の座標にchoice(16)を置く
                        if target_pos[0] == choice_pos[0]:
                            target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                        else:
                            while target_pos[0]-1 != choice_pos[0]:
                                target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                        #targetの右上にchoice(16)を置く
                        if target_pos[1] >= choice_pos[1]:
                            while target_pos[1]+1 != choice_pos[1]:
                                target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                        else:
                            while target_pos[1]+1 != choice_pos[1]:
                                target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)

                        #targetを置きたい座標のx座標と同じになるまで移動
                        target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                        while target_pos[1] != pos[1]+1:
                            target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)

                    #targetが最終的におきたいx座標の右と同じ
                    elif target_pos[1] == pos[1]+1:
                        #targetの上の座標にchoice(16)を置く
                        if target_pos[0] == choice_pos[0]:
                            target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                        else:
                            while target_pos[0]-1 != choice_pos[0]:
                                target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                        #targetの上にchoice(16)を移動
                        while target_pos[1] != choice_pos[1]:
                            target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)

                    #targetを最終的に置きたいy座標まで移動
                    target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                    while target_pos[0] != pos[0]:
                        target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)


                #最終的に置きたい位置が右端
                elif j == row - 1:
                    #targetが最終的におきたいx座標よりも左
                    if target_pos[1] < pos[1]:
                        #targetの上の座標にchoice(16)を置く
                        if target_pos[0] == choice_pos[0]:
                            target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                        else:
                            while target_pos[0]-1 != choice_pos[0]:
                                target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                        #targetの右上にchoice(16)を置く
                        if target_pos[1] >= choice_pos[1]:
                            while target_pos[1]+1 != choice_pos[1]:
                                target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                        else:
                            while target_pos[1]+1 != choice_pos[1]:
                                target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)

                        #targetを置きたい座標のx座標と同じになるまで移動
                        target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                        while target_pos[1] != pos[1]:
                            target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)

                    #targetが最終的におきたいx座標と同じ
                    elif target_pos[1] == choice_pos[1]:
                        #targetの上の座標にchoice(16)を置く
                        if target_pos[0] == choice_pos[0]:
                            target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                        else:
                            while target_pos[0]-1 != choice_pos[0]:
                                target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                        #targetの上にchoice(16)を移動
                        while target_pos[1] != choice_pos[1]:
                            target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                    
                    #targetを最終的に置きたいy座標まで移動
                    target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                    while target_pos[0] != pos[0]+1:
                        target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                    
                    #3,4を最終的におきたい座標となるよう移動
                    target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                    target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                    target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                    target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                    target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)

            print("交換回数：" + str(exchange))    

            print(split_list)
            print()
            print("       ↓")
            print()
            

    #さいごの2行（たいち）
    

    return exchange

exchange = move(split_list, exchange)
print("交換回数：" + str(exchange))
print(split_list)



[[ 1  2 15  4]
 [ 5  6 10  8]
 [14 12  9  7]
 [13 11 16  3]]

       ↓

target_num = 1----------------------------------------------------------
[[ 1  2 15  4]
 [ 5  6 10  8]
 [14 12  9  7]
 [13 16 11  3]]

[[ 1  2 15  4]
 [ 5  6 10  8]
 [14 16  9  7]
 [13 12 11  3]]

[[ 1  2 15  4]
 [ 5 16 10  8]
 [14  6  9  7]
 [13 12 11  3]]

[[ 1 16 15  4]
 [ 5  2 10  8]
 [14  6  9  7]
 [13 12 11  3]]

交換回数：4
[[ 1 16 15  4]
 [ 5  2 10  8]
 [14  6  9  7]
 [13 12 11  3]]

       ↓

target_num = 2----------------------------------------------------------
[[ 1 15 16  4]
 [ 5  2 10  8]
 [14  6  9  7]
 [13 12 11  3]]

[[ 1 15 10  4]
 [ 5  2 16  8]
 [14  6  9  7]
 [13 12 11  3]]

[[ 1 15 16  4]
 [ 5  2 10  8]
 [14  6  9  7]
 [13 12 11  3]]

[[ 1 16 15  4]
 [ 5  2 10  8]
 [14  6  9  7]
 [13 12 11  3]]

[[ 1  2 15  4]
 [ 5 16 10  8]
 [14  6  9  7]
 [13 12 11  3]]

交換回数：9
[[ 1  2 15  4]
 [ 5 16 10  8]
 [14  6  9  7]
 [13 12 11  3]]

       ↓

target_num = 3----------------------------------------------------

In [50]:
import random
s = random.sample(range(1, 17), 16)
ss = np.array(s)
type(ss)
sss = ss.reshape(4, 4)
print(sss)

[[11 14  2 10]
 [ 6 16  7  5]
 [ 9 12 13  3]
 [ 8 15  1  4]]
