In [11]:
import numpy as np

In [50]:
#上下左右に移動する関数
def up(target_num, choice_num, exchange):
    target_pos = tuple(nd[0] for nd in np.where(split_list == target_num))
    choice_pos = tuple(nd[0] for nd in np.where(split_list == choice_num))

    np.put(split_list, [4 * choice_pos[0] + choice_pos[1]], split_list[choice_pos[0]-1][choice_pos[1]])
    np.put(split_list, [4 * choice_pos[0] + choice_pos[1] - 4], choice_num)
    
    target_pos = tuple(nd[0] for nd in np.where(split_list == target_num))
    choice_pos = tuple(nd[0] for nd in np.where(split_list == choice_num))
    exchange += 1
    return target_pos, choice_pos, exchange

def down(target_num, choice_num, exchange):
    target_pos = tuple(nd[0] for nd in np.where(split_list == target_num))
    choice_pos = tuple(nd[0] for nd in np.where(split_list == choice_num))

    np.put(split_list, [4 * (choice_pos[0]) + choice_pos[1]], split_list[choice_pos[0]+1][choice_pos[1]])
    np.put(split_list, [4 * (choice_pos[0]) + choice_pos[1] + 4], choice_num)
    
    target_pos = tuple(nd[0] for nd in np.where(split_list == target_num))
    choice_pos = tuple(nd[0] for nd in np.where(split_list == choice_num))
    exchange += 1
    return target_pos, choice_pos, exchange

def right(target_num, choice_num, exchange):
    target_pos = tuple(nd[0] for nd in np.where(split_list == target_num))
    choice_pos = tuple(nd[0] for nd in np.where(split_list == choice_num))

    np.put(split_list, [4 * (choice_pos[0]) + choice_pos[1]], split_list[choice_pos[0]][choice_pos[1]+1])
    np.put(split_list, [4 * (choice_pos[0]) + choice_pos[1] + 1], choice_num)
    
    target_pos = tuple(nd[0] for nd in np.where(split_list == target_num))
    choice_pos = tuple(nd[0] for nd in np.where(split_list == choice_num))
    exchange += 1
    return target_pos, choice_pos, exchange

def left(target_num, choice_num, exchange):
    target_pos = tuple(nd[0] for nd in np.where(split_list == target_num))
    choice_pos = tuple(nd[0] for nd in np.where(split_list == choice_num))

    np.put(split_list, [4 * (choice_pos[0]) + choice_pos[1]], split_list[choice_pos[0]][choice_pos[1]-1])
    np.put(split_list, [4 * (choice_pos[0]) + choice_pos[1] -1], choice_num)
    
    target_pos = tuple(nd[0] for nd in np.where(split_list == target_num))
    choice_pos = tuple(nd[0] for nd in np.where(split_list == choice_num))
    exchange += 1
    return target_pos, choice_pos, exchange

In [169]:
#これをメインの処理にする_

split_list = np.array([[14, 12, 8, 1],
                       [13, 2, 3, 6],
                       [11, 4, 9, 5],
                       [16, 15, 7, 10]])
print(split_list)
print()
print("       ↓")
print()

exchange = 0

def move(split_list, exchange):
    columns = split_list.shape[0]
    row = split_list.shape[1]

    #最後2行を除いて並び替え（たくと）
    for i in range(columns - 2):
        for j in range(row):
            target_num = i * row + j + 1
            choice_num = columns * row

            target_pos = tuple(nd[0] for nd in np.where(split_list == target_num))
            choice_pos = tuple(nd[0] for nd in np.where(split_list == choice_num))

            if target_num % row == 0: pos = (target_num // row - 1, row - 1)
            else: pos = (target_num // row, target_num % row - 1)

            if target_pos[0] != columns-1:
                #右2列を除いた列を並び替え
                if j != row - 1 or j != row - 2:
                    if target_pos[1] > pos[1]:
                        #targetの左下にchoice(16)を置く
                        if target_pos[1] <= choice_pos[1]:
                            while target_pos[1]-1 != choice_pos[1]:
                                target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                        else:
                            while target_pos[1]-1 != choice_pos[1]:
                                target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                        while target_pos[0]+1 != choice_pos[0]:
                            target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)

                        #targetを置きたい座標のx座標と同じになるまで移動
                        if target_pos[1] != pos[1]:
                            target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                            while target_pos[1] != pos[1]:
                                target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                                target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                                target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                                target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                                target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                        #targetを置きたい座標のy座標と同じになるまで移動
                        if target_pos[0] != pos[0]:
                            target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                            while target_pos[0] != pos[0]:
                                target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                                target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                                target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                                target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                                target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)

            elif j == row - 1:


            elif j == row - 2:


            print("target_num = " + str(target_num))
            print(split_list)
            print()
            print("       ↓")
            print()
            

    #さいごの2行（たいち）
    

    return exchange

exchange = move(split_list, exchange)
print(exchange)
print(split_list)



[[14 12  8  1]
 [13  2  3  6]
 [11  4  9  5]
 [16 15  7 10]]

       ↓

target_num = 1
[[ 1 16  2  6]
 [14 13 12  8]
 [11  4  3  5]
 [15  7  9 10]]

       ↓

target_num = 2
[[ 1  2 16  6]
 [14  7 12  8]
 [11 13  3  5]
 [15  4  9 10]]

       ↓

target_num = 3
[[ 1  2 16  6]
 [14  7 12  8]
 [11 13  3  5]
 [15  4  9 10]]

       ↓

target_num = 4
[[ 1  2 16  6]
 [14  7 12  8]
 [11 13  3  5]
 [15  4  9 10]]

       ↓

target_num = 5
[[ 1  2  9  6]
 [ 5 14 12  8]
 [16  7  4 10]
 [11 15 13  3]]

       ↓



IndexError: index 4 is out of bounds for axis 0 with size 4