In [38]:
import numpy as np
import random
import copy

#上下左右に移動する関数
def up(target_num, choice_num, exchange):
    target_pos = tuple(nd[0] for nd in np.where(split_list == target_num))
    choice_pos = tuple(nd[0] for nd in np.where(split_list == choice_num))

    np.put(split_list, [4 * choice_pos[0] + choice_pos[1]], split_list[choice_pos[0]-1][choice_pos[1]])
    np.put(split_list, [4 * choice_pos[0] + choice_pos[1] - 4], choice_num)
    
    target_pos = tuple(nd[0] for nd in np.where(split_list == target_num))
    choice_pos = tuple(nd[0] for nd in np.where(split_list == choice_num))
    exchange += 1

    return target_pos, choice_pos, exchange

def down(target_num, choice_num, exchange):
    target_pos = tuple(nd[0] for nd in np.where(split_list == target_num))
    choice_pos = tuple(nd[0] for nd in np.where(split_list == choice_num))

    np.put(split_list, [4 * (choice_pos[0]) + choice_pos[1]], split_list[choice_pos[0]+1][choice_pos[1]])
    np.put(split_list, [4 * (choice_pos[0]) + choice_pos[1] + 4], choice_num)
    
    target_pos = tuple(nd[0] for nd in np.where(split_list == target_num))
    choice_pos = tuple(nd[0] for nd in np.where(split_list == choice_num))

    return target_pos, choice_pos, exchange

def right(target_num, choice_num, exchange):
    target_pos = tuple(nd[0] for nd in np.where(split_list == target_num))
    choice_pos = tuple(nd[0] for nd in np.where(split_list == choice_num))

    np.put(split_list, [4 * (choice_pos[0]) + choice_pos[1]], split_list[choice_pos[0]][choice_pos[1]+1])
    np.put(split_list, [4 * (choice_pos[0]) + choice_pos[1] + 1], choice_num)
    
    target_pos = tuple(nd[0] for nd in np.where(split_list == target_num))
    choice_pos = tuple(nd[0] for nd in np.where(split_list == choice_num))
    exchange += 1

    return target_pos, choice_pos, exchange

def left(target_num, choice_num, exchange):
    target_pos = tuple(nd[0] for nd in np.where(split_list == target_num))
    choice_pos = tuple(nd[0] for nd in np.where(split_list == choice_num))

    np.put(split_list, [4 * (choice_pos[0]) + choice_pos[1]], split_list[choice_pos[0]][choice_pos[1]-1])
    np.put(split_list, [4 * (choice_pos[0]) + choice_pos[1] -1], choice_num)
    
    target_pos = tuple(nd[0] for nd in np.where(split_list == target_num))
    choice_pos = tuple(nd[0] for nd in np.where(split_list == choice_num))
    exchange += 1

    return target_pos, choice_pos, exchange


#並び替え関数
def move(split_list, exchange):
    columns = split_list.shape[0]
    row = split_list.shape[1]

    #最後2行を除いて並び替え（たくと）
    for i in range(columns - 2):
        for j in range(row):
            target_num = i * row + j + 1
            choice_num = columns * row

            target_pos = tuple(nd[0] for nd in np.where(split_list == target_num))
            choice_pos = tuple(nd[0] for nd in np.where(split_list == choice_num))

            print("target_num = " + str(target_num) + "----------------------------------------------------------")

            #最終的に置きたい座標
            if target_num % row == 0: pos = (target_num // row - 1, row - 1)
            else: pos = (target_num // row, target_num % row - 1)

            #targetが下端でない
            if target_pos[0] != columns-1:
                #右2列を除いた列を並び替え
                if j != row - 1 and j != row - 2:
                    #targetが最終的に置きたいx座標よりも右
                    if target_pos[1] > pos[1]:
                        #targetの左下にchoice(16)を置く
                        if target_pos[1] <= choice_pos[1]:
                            while target_pos[1]-1 != choice_pos[1]:
                                target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                        else:
                            while target_pos[1]-1 != choice_pos[1]:
                                target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                        #targetを最終的に置きたいy座標に移動
                        if target_pos[0] < choice_pos[0]:
                            while target_pos[0]+1 != choice_pos[0]:
                                target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                        else:
                            while target_pos[0]+1 != choice_pos[0]:
                                target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)

                        #targetを置きたい座標のx座標と同じになるまで移動
                        if target_pos[1] != pos[1]:
                            target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                            while target_pos[1] != pos[1]:
                                target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                                target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                                target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                                target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                                target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                    
                    #targetを最終的に置きたいx座標よりも左
                    elif target_pos[1] < pos[1]:
                        #targetの右下にchoice(16)を置く
                        if target_pos[1] >= choice_pos[1]:
                            while target_pos[1]+1 != choice_pos[1]:
                                target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                        else:
                            while target_pos[1]+1 != choice_pos[1]:
                                target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                        while target_pos[0]+1 != choice_pos[0]:
                            target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                        #targetを置きたい座標のx座標と同じになるまで移動
                        if target_pos[1] != pos[1]:
                            target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                            while target_pos[1] != pos[1]:
                                target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                                target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                                target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                                target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                                target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                            #targetの右にchoice(16)をおく
                            target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                        
                    
                    #targetが最終的に置きたいx座標と同じ
                    elif target_pos[1] == pos[1]:
                        #targetの右にchoice(16)をおく
                        #targetよりchoiceが右
                        if target_pos[1] < choice_pos[1]:
                            while target_pos[1]+1 != choice_pos[1]:
                                target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                            #targetよりchoiceが上
                            if target_pos[0] > choice_pos[0]:
                                while target_pos[0] != choice_pos[0]:
                                    target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                            #targetよりchoiceが下
                            else:
                                while target_pos[0] != choice_pos[0]:
                                    target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)

                        #targetよりchoiceが左
                        elif target_pos[1] > choice_pos[1]:
                            #targetがchoiceより上or下
                            if target_pos[0] != choice_pos[0]:
                                while target_pos[1]+1 != choice_pos[1]:
                                    target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                                #targetよりchoiceが上
                                if target_pos[0] > choice_pos[0]:
                                    while target_pos[0] != choice_pos[0]:
                                        target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                                #targetよりchoiceが下
                                else:
                                    while target_pos[0] != choice_pos[0]:
                                        target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                            #targetがchoiceと同じx座標
                            else:
                                target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                                while target_pos[1]+1 != choice_pos[1]:
                                    target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                                target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                        
                        #targetとchoiceのx座標が同じ
                        else:
                            target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                            #targetよりchoiceが上
                            if target_pos[0] > choice_pos[0]:
                                while target_pos[0] != choice_pos[0]:
                                    target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                            #targetよりchoiceが下
                            else:
                                while target_pos[0] != choice_pos[0]:
                                    target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)

                         
                    #targetを置きたい座標のy座標と同じになるまで移動
                    if target_pos[0] != pos[0]:
                        target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                        while target_pos[0] != pos[0]:
                            target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                
                #最終的に置きたい位置が右から2列目
                elif j == row - 2:
                    #最終的に置きたい座標にある
                    if target_pos[0] == pos[0] and target_pos[1] == pos[1]:
                        while target_pos[1]+1 != choice_pos[1]:
                            target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                        while target_pos[0] != choice_pos[0]:
                            target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)

                    #最終的に置きたいy座標でない
                    elif target_pos[0] != pos[0]:
                        #最終的におきたいx座標でない
                        if target_pos[1] != pos[1]+1:
                            #targetよりも下にchoiceがある
                            if target_pos[0] < choice_pos[0]:
                                while target_pos[0]+1 != choice_pos[0]:
                                    target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                            #targetよりも上にchoiceがある
                            elif target_pos[0] > choice_pos[0]:
                                while target_pos[0]+1 != choice_pos[0]:
                                    target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)

                            #targetの右にchoiceを移動
                            #targetよりも右にchoiceがある
                            if target_pos[1] < choice_pos[1]:
                                while target_pos[1]+1 != choice_pos[1]:
                                    target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                            #targetよりも左にchoiceがある
                            else:
                                while target_pos[1]+1 != choice_pos[1]:
                                    target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                            
                            
                            #targetを右端まで移動
                            target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                            while target_pos[1] != pos[1]+1:
                                target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                                target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                                target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                                target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                                target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                            #targetを最終的に置きたいy座標まで移動
                            target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                            while target_pos[0] != pos[0]:
                                target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                                target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                                target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                                target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                                target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)

                        #最終的におきたいx座標にある
                        elif target_pos[1] == pos[1]+1: 
                            #targetのx座標の左にchoiceを移動
                            if target_pos[1] == choice_pos[1]:
                                target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                            else:
                                while target_pos[1]-1 != choice_pos[1]:
                                    target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)

                            #targetの左上に移動
                            #targetよりも下にchoiceがある
                            if target_pos[0] <= choice_pos[0]:
                                while target_pos[0]-1 != choice_pos[0]:
                                    target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                            #targetよりも上にchoiceがある
                            else:
                                while target_pos[0]-1 != choice_pos[0]:
                                    target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)

                            #targetを最終的に置きたいy座標まで移動
                            target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                            while target_pos[0] != pos[0]:
                                target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                                target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                                target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                                target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                                target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)


                #最終的に置きたい位置が右端
                elif j == row - 1:

                    #逆順に並んでいる
                    if target_pos[0] == pos[0] and target_pos[1] == pos[1]-1:
                        target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)

                    #targetがtarget-1の下
                    elif target_pos[0] == pos[0]+1 and target_pos[1] == pos[1]:
                        #targetの左にchoice
                        #targetの左の座標に移動
                        if target_pos[1] > choice_pos[1]:
                            while target_pos[1]-1 != choice_pos[1]:
                                target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                        else:
                            while target_pos[1]-1 != choice_pos[1]:
                                target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                        #targetの左上に移動
                        if target_pos[0] < choice_pos[0]:
                            while target_pos[0]-1 != choice_pos[0]:
                                target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                        
                        #3,4を最終的に置きたい座標となるよう移動
                        target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)

                    elif target_pos[0] != pos[0]+1 or target_pos[1] != pos[1]:
                        #targetの上にchoiceがある
                        if target_pos[0] > choice_pos[0]:
                            while target_pos[0]+1 != choice_pos[0]:
                                target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                        #targetの下にchoiceがある
                        else:
                            while target_pos[0]+1 != choice_pos[0]:
                                target_pos, choice_pos, exchange = up(target_num, choice_num, exchange) 

                        #targetの右にchoiceがある
                        if target_pos[1] < choice_pos[1]:
                            while target_pos[1] != choice_pos[1]:
                                target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                        #targetの左にchoiceがある
                        elif target_pos[1] > choice_pos[1]:
                            while target_pos[1] != choice_pos[1]:
                                target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)

                        

                        #targetを右端まで移動
                        if target_pos[1] != pos[1]:
                            target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                        else:
                            target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                        while target_pos[1] != pos[1]:
                            target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)

                        #targetをtarget-1の下に移動
                        if target_pos[0] != pos[0]+1:
                            while target_pos[0] != pos[0]+1:
                                target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                                target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                                target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                                target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                                target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)

                        #3,4を最終的に置きたい座標となるよう移動
                        target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)                 


            #targetが下端
            else:
                #右2列を除いた列を並び替え
                if j != row - 1 and j != row - 2:
                    #targetが最終的におきたいx座標よりも右
                    if target_pos[1] > pos[1]:
                        #targetの上の座標にchoice(16)を置く
                        if target_pos[0] == choice_pos[0]:
                            target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                        else:
                            while target_pos[0]-1 != choice_pos[0]:
                                target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                        #targetの左上にchoice(16)を置く
                        if target_pos[1] <= choice_pos[1]:
                            while target_pos[1]-1 != choice_pos[1]:
                                target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                        else:
                            while target_pos[1]-1 != choice_pos[1]:
                                target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                        
                        #targetをおきたい座標のx座標と同じになるまで移動
                        target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                        while target_pos[1] != pos[1]:
                            target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                        #targetの上にchoiceを置く
                        target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)

                    #targetが最終的におきたいx座標よりも左
                    elif target_pos[1] < pos[1]:
                        #targetの上の座標にchoice(16)を置く
                        if target_pos[0] == choice_pos[0]:
                            target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                        else:
                            while target_pos[0]-1 != choice_pos[0]:
                                target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                        #targetの右上にchoice(16)を置く
                        if target_pos[1] >= choice_pos[1]:
                            while target_pos[1]+1 != choice_pos[1]:
                                target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                        else:
                            while target_pos[1]+1 != choice_pos[1]:
                                target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)

                        #targetを置きたい座標のx座標と同じになるまで移動
                        target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                        while target_pos[1] != pos[1]:
                            target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)

                        #targetの上にchoic(16)を置く
                        target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)

                    #targetが最終的におきたいx座標と同じ
                    else:
                        #targetの上の座標にchoice(16)を置く
                        if target_pos[0] == choice_pos[0]:
                            target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                        else:
                            while target_pos[0]-1 != choice_pos[0]:
                                target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)

                        #targetの上にchoiceを置く
                        if target_pos[1] < choice_pos[1]:
                            while target_pos[1] != choice_pos[1]:
                                target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)   
                        elif target_pos[1] > choice_pos[1]:
                            while target_pos[1] != choice_pos[1]:
                                target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)   

                    #targetを置きたい座標のy座標になるまで移動
                    if target_pos[0] != pos[0]:
                        target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                        while target_pos[0] != pos[0]:
                            target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                
                #最終的に置きたい位置が右から2列目
                elif j == row - 2:
                    #targetが最終的におきたいx座標よりも左
                    if target_pos[1] < pos[1]+1:
                        #targetの上の座標にchoice(16)を置く
                        if target_pos[0] == choice_pos[0]:
                            target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                        else:
                            while target_pos[0]-1 != choice_pos[0]:
                                target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                        #targetの右上にchoice(16)を置く
                        if target_pos[1] >= choice_pos[1]:
                            while target_pos[1]+1 != choice_pos[1]:
                                target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                        else:
                            while target_pos[1]+1 != choice_pos[1]:
                                target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)

                        #targetを置きたい座標のx座標と同じになるまで移動
                        target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                        while target_pos[1] != pos[1]+1:
                            target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)

                    #targetが最終的におきたいx座標の右と同じ
                    elif target_pos[1] == pos[1]+1:
                        #targetの上の座標にchoice(16)を置く
                        if target_pos[0] == choice_pos[0]:
                            target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                        else:
                            while target_pos[0]-1 != choice_pos[0]:
                                target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                        #targetの上にchoice(16)を移動
                        while target_pos[1] != choice_pos[1]:
                            target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)

                    #targetを最終的に置きたいy座標まで移動
                    target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                    while target_pos[0] != pos[0]:
                        target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)


                #最終的に置きたい位置が右端
                elif j == row - 1:
                    #targetが最終的におきたいx座標よりも左
                    if target_pos[1] < pos[1]:
                        #targetの上の座標にchoice(16)を置く
                        if target_pos[0] == choice_pos[0]:
                            target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                        else:
                            while target_pos[0]-1 != choice_pos[0]:
                                target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                        #targetの右上にchoice(16)を置く
                        if target_pos[1] >= choice_pos[1]:
                            while target_pos[1]+1 != choice_pos[1]:
                                target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                        else:
                            while target_pos[1]+1 != choice_pos[1]:
                                target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)

                        #targetを置きたい座標のx座標と同じになるまで移動
                        target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                        while target_pos[1] != pos[1]:
                            target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)

                    #targetが最終的におきたいx座標と同じ
                    elif target_pos[1] == pos[1]:
                        #targetの上の座標にchoice(16)を置く
                        if target_pos[0] == choice_pos[0]:
                            target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                        else:
                            while target_pos[0]-1 != choice_pos[0]:
                                target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                        #targetの上にchoice(16)を移動
                        while target_pos[1] != choice_pos[1]:
                            target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                    
                    #targetを最終的に置きたいy座標まで移動
                    target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                    while target_pos[0] != pos[0]+1:
                        target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                    
                    #3,4を最終的におきたい座標となるよう移動
                    target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                    target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                    target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                    target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                    target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)

            print("交換回数：" + str(exchange))    

            print(split_list)
            print()
            print("       ↓")
            print()
        

    #さいごの2行（たいち）
    

    return exchange



#メイン
#ファイルオープン
# f = open('画像問題フォーマット.txt', 'r', encoding='UTF-8')
# data = f.readlines()
# f.close()

# s0 = data[0].rstrip('\n').rstrip(',')
# s1 = data[1].rstrip('\n').rstrip(',')
# s2 = data[2].rstrip('\n').rstrip(',')
# s3 = data[3].rstrip('\n').rstrip(',')
# s4 = data[4].rstrip('\n').rstrip(',')

# l0 = [int(x.strip()) for x in s0.split(',')]
# l1 = [int(x.strip()) for x in s1.split(',')]
# l2 = [int(x.strip()) for x in s2.split(',')]
# l3 = [int(x.strip()) for x in s3.split(',')]
# l4 = [int(x.strip()) for x in s4.split(',')]

# split_list = np.array([l1, l2, l3, l4])
# print(l0)


random_num = random.sample(range(1, 17), 16)
random_list = np.array(random_num)
split_list = random_list.reshape(4, 4)

copy_list = copy.copy(split_list)

print(split_list)
print()
print("       ↓")
print()

exchange = 0
exchange = move(split_list, exchange)
print("交換回数：" + str(exchange))
print(split_list)

[[ 2 11  3  4]
 [ 6  5  7 15]
 [10  1 12 14]
 [ 8 16  9 13]]

       ↓

target_num = 1----------------------------------------------------------
交換回数：9
[[ 1  2  3  4]
 [16 11  7 15]
 [ 5  6 12 14]
 [10  8  9 13]]

       ↓

target_num = 2----------------------------------------------------------
交換回数：12
[[ 1  2 16  4]
 [11  7  3 15]
 [ 5  6 12 14]
 [10  8  9 13]]

       ↓

target_num = 3----------------------------------------------------------


IndexError: index 4 is out of bounds for axis 0 with size 4

In [42]:
#エラー用コード


#上下左右に移動する関数
def up(target_num, choice_num, exchange):
    target_pos = tuple(nd[0] for nd in np.where(split_list == target_num))
    choice_pos = tuple(nd[0] for nd in np.where(split_list == choice_num))

    np.put(split_list, [4 * choice_pos[0] + choice_pos[1]], split_list[choice_pos[0]-1][choice_pos[1]])
    np.put(split_list, [4 * choice_pos[0] + choice_pos[1] - 4], choice_num)
    
    target_pos = tuple(nd[0] for nd in np.where(split_list == target_num))
    choice_pos = tuple(nd[0] for nd in np.where(split_list == choice_num))
    exchange += 1
    print(split_list)
    print("")
    return target_pos, choice_pos, exchange

def down(target_num, choice_num, exchange):
    target_pos = tuple(nd[0] for nd in np.where(split_list == target_num))
    choice_pos = tuple(nd[0] for nd in np.where(split_list == choice_num))

    np.put(split_list, [4 * (choice_pos[0]) + choice_pos[1]], split_list[choice_pos[0]+1][choice_pos[1]])
    np.put(split_list, [4 * (choice_pos[0]) + choice_pos[1] + 4], choice_num)
    
    target_pos = tuple(nd[0] for nd in np.where(split_list == target_num))
    choice_pos = tuple(nd[0] for nd in np.where(split_list == choice_num))
    print(split_list)
    print("")
    return target_pos, choice_pos, exchange

def right(target_num, choice_num, exchange):
    target_pos = tuple(nd[0] for nd in np.where(split_list == target_num))
    choice_pos = tuple(nd[0] for nd in np.where(split_list == choice_num))

    np.put(split_list, [4 * (choice_pos[0]) + choice_pos[1]], split_list[choice_pos[0]][choice_pos[1]+1])
    np.put(split_list, [4 * (choice_pos[0]) + choice_pos[1] + 1], choice_num)
    
    target_pos = tuple(nd[0] for nd in np.where(split_list == target_num))
    choice_pos = tuple(nd[0] for nd in np.where(split_list == choice_num))
    exchange += 1
    print(split_list)
    print("")
    return target_pos, choice_pos, exchange

def left(target_num, choice_num, exchange):
    target_pos = tuple(nd[0] for nd in np.where(split_list == target_num))
    choice_pos = tuple(nd[0] for nd in np.where(split_list == choice_num))

    np.put(split_list, [4 * (choice_pos[0]) + choice_pos[1]], split_list[choice_pos[0]][choice_pos[1]-1])
    np.put(split_list, [4 * (choice_pos[0]) + choice_pos[1] -1], choice_num)
    
    target_pos = tuple(nd[0] for nd in np.where(split_list == target_num))
    choice_pos = tuple(nd[0] for nd in np.where(split_list == choice_num))
    exchange += 1
    print(split_list)
    print("")
    return target_pos, choice_pos, exchange


def move(split_list, exchange):
    columns = split_list.shape[0]
    row = split_list.shape[1]

    #最後2行を除いて並び替え（たくと）
    for i in range(columns - 2):
        for j in range(row):
            target_num = i * row + j + 1
            choice_num = columns * row

            target_pos = tuple(nd[0] for nd in np.where(split_list == target_num))
            choice_pos = tuple(nd[0] for nd in np.where(split_list == choice_num))

            print("target_num = " + str(target_num) + "----------------------------------------------------------")

            #最終的に置きたい座標
            if target_num % row == 0: pos = (target_num // row - 1, row - 1)
            else: pos = (target_num // row, target_num % row - 1)

            #targetが下端でない
            if target_pos[0] != columns-1:
                #右2列を除いた列を並び替え
                if j != row - 1 and j != row - 2:
                    #targetが最終的に置きたいx座標よりも右
                    if target_pos[1] > pos[1]:
                        #targetの左下にchoice(16)を置く
                        if target_pos[1] <= choice_pos[1]:
                            while target_pos[1]-1 != choice_pos[1]:
                                target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                        else:
                            while target_pos[1]-1 != choice_pos[1]:
                                target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                        #targetを最終的に置きたいy座標に移動
                        if target_pos[0] < choice_pos[0]:
                            while target_pos[0]+1 != choice_pos[0]:
                                target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                        else:
                            while target_pos[0]+1 != choice_pos[0]:
                                target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)

                        #targetを置きたい座標のx座標と同じになるまで移動
                        if target_pos[1] != pos[1]:
                            target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                            while target_pos[1] != pos[1]:
                                target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                                target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                                target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                                target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                                target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                    
                    #targetを最終的に置きたいx座標よりも左
                    elif target_pos[1] < pos[1]:
                        #targetの右下にchoice(16)を置く
                        if target_pos[1] >= choice_pos[1]:
                            while target_pos[1]+1 != choice_pos[1]:
                                target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                        else:
                            while target_pos[1]+1 != choice_pos[1]:
                                target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                        while target_pos[0]+1 != choice_pos[0]:
                            target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                        #targetを置きたい座標のx座標と同じになるまで移動
                        if target_pos[1] != pos[1]:
                            target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                            while target_pos[1] != pos[1]:
                                target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                                target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                                target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                                target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                                target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                            #targetの右にchoice(16)をおく
                            target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                        
                    
                    #targetが最終的に置きたいx座標と同じ
                    elif target_pos[1] == pos[1]:
                        #targetの右にchoice(16)をおく
                        #targetよりchoiceが右
                        if target_pos[1] < choice_pos[1]:
                            while target_pos[1]+1 != choice_pos[1]:
                                target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                            #targetよりchoiceが上
                            if target_pos[0] > choice_pos[0]:
                                while target_pos[0] != choice_pos[0]:
                                    target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                            #targetよりchoiceが下
                            else:
                                while target_pos[0] != choice_pos[0]:
                                    target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)

                        #targetよりchoiceが左
                        elif target_pos[1] > choice_pos[1]:
                            #targetがchoiceより上or下
                            if target_pos[0] != choice_pos[0]:
                                while target_pos[1]+1 != choice_pos[1]:
                                    target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                                #targetよりchoiceが上
                                if target_pos[0] > choice_pos[0]:
                                    while target_pos[0] != choice_pos[0]:
                                        target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                                #targetよりchoiceが下
                                else:
                                    while target_pos[0] != choice_pos[0]:
                                        target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                            #targetがchoiceと同じx座標
                            else:
                                target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                                while target_pos[1]+1 != choice_pos[1]:
                                    target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                                target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                        
                        #targetとchoiceのx座標が同じ
                        else:
                            target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                            #targetよりchoiceが上
                            if target_pos[0] > choice_pos[0]:
                                while target_pos[0] != choice_pos[0]:
                                    target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                            #targetよりchoiceが下
                            else:
                                while target_pos[0] != choice_pos[0]:
                                    target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)

                         
                    #targetを置きたい座標のy座標と同じになるまで移動
                    if target_pos[0] != pos[0]:
                        target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                        while target_pos[0] != pos[0]:
                            target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                
                #最終的に置きたい位置が右から2列目
                elif j == row - 2:
                    #最終的に置きたい座標にある
                    if target_pos[0] == pos[0] and target_pos[1] == pos[1]:
                        while target_pos[1]+1 != choice_pos[1]:
                            target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                        while target_pos[0] != choice_pos[0]:
                            target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)

                    #最終的に置きたいy座標でない
                    elif target_pos[0] != pos[0]:
                        #最終的におきたいx座標でない
                        if target_pos[1] != pos[1]+1:
                            #targetよりも下にchoiceがある
                            if target_pos[0] < choice_pos[0]:
                                while target_pos[0]+1 != choice_pos[0]:
                                    target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                            #targetよりも上にchoiceがある
                            elif target_pos[0] > choice_pos[0]:
                                while target_pos[0]+1 != choice_pos[0]:
                                    target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)

                            #targetの右にchoiceを移動
                            #targetよりも右にchoiceがある
                            if target_pos[1] < choice_pos[1]:
                                while target_pos[1]+1 != choice_pos[1]:
                                    target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                            #targetよりも左にchoiceがある
                            else:
                                while target_pos[1]+1 != choice_pos[1]:
                                    target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                            
                            
                            #targetを右端まで移動
                            target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                            while target_pos[1] != pos[1]+1:
                                target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                                target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                                target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                                target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                                target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                            #targetを最終的に置きたいy座標まで移動
                            target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                            while target_pos[0] != pos[0]:
                                target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                                target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                                target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                                target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                                target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)

                        #最終的におきたいx座標にある
                        elif target_pos[1] == pos[1]+1: 
                            #targetのx座標の左にchoiceを移動
                            if target_pos[1] == choice_pos[1]:
                                target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                            else:
                                while target_pos[1]-1 != choice_pos[1]:
                                    target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)

                            #targetの左上に移動
                            #targetよりも下にchoiceがある
                            if target_pos[0] <= choice_pos[0]:
                                while target_pos[0]-1 != choice_pos[0]:
                                    target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                            #targetよりも上にchoiceがある
                            else:
                                while target_pos[0]-1 != choice_pos[0]:
                                    target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)

                            #targetを最終的に置きたいy座標まで移動
                            target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                            while target_pos[0] != pos[0]:
                                target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                                target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                                target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                                target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                                target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)


                #最終的に置きたい位置が右端
                elif j == row - 1:

                    #逆順に並んでいる
                    if target_pos[0] == pos[0] and target_pos[1] == pos[1]-1:
                        target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)

                    #targetがtarget-1の下
                    elif target_pos[0] == pos[0]+1 and target_pos[1] == pos[1]:
                        #targetの左にchoice
                        #targetの左の座標に移動
                        if target_pos[1] > choice_pos[1]:
                            while target_pos[1]-1 != choice_pos[1]:
                                target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                        else:
                            while target_pos[1]-1 != choice_pos[1]:
                                target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                        #targetの左上に移動
                        if target_pos[0] < choice_pos[0]:
                            while target_pos[0]-1 != choice_pos[0]:
                                target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                        
                        #3,4を最終的に置きたい座標となるよう移動
                        target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)

                    elif target_pos[0] != pos[0]+1 or target_pos[1] != pos[1]:
                        #targetの上にchoiceがある
                        if target_pos[0] > choice_pos[0]:
                            while target_pos[0]+1 != choice_pos[0]:
                                target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                        #targetの下にchoiceがある
                        else:
                            while target_pos[0]+1 != choice_pos[0]:
                                target_pos, choice_pos, exchange = up(target_num, choice_num, exchange) 

                        #targetの右にchoiceがある
                        if target_pos[1] < choice_pos[1]:
                            while target_pos[1] != choice_pos[1]:
                                target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                        #targetの左にchoiceがある
                        elif target_pos[1] > choice_pos[1]:
                            while target_pos[1] != choice_pos[1]:
                                target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)

                        

                        #targetを右端まで移動
                        if target_pos[1] != pos[1]:
                            target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                        else:
                            target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                        while target_pos[1] != pos[1]:
                            target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)

                        #targetをtarget-1の下に移動
                        if target_pos[0] != pos[0]+1:
                            while target_pos[0] != pos[0]+1:
                                target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                                target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                                target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                                target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                                target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)

                        #3,4を最終的に置きたい座標となるよう移動
                        target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)                 


            #targetが下端
            else:
                #右2列を除いた列を並び替え
                if j != row - 1 and j != row - 2:
                    #targetが最終的におきたいx座標よりも右
                    if target_pos[1] > pos[1]:
                        #targetの上の座標にchoice(16)を置く
                        if target_pos[0] == choice_pos[0]:
                            target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                        else:
                            while target_pos[0]-1 != choice_pos[0]:
                                target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                        #targetの左上にchoice(16)を置く
                        if target_pos[1] <= choice_pos[1]:
                            while target_pos[1]-1 != choice_pos[1]:
                                target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                        else:
                            while target_pos[1]-1 != choice_pos[1]:
                                target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                        
                        #targetをおきたい座標のx座標と同じになるまで移動
                        target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                        while target_pos[1] != pos[1]:
                            target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                        #targetの上にchoiceを置く
                        target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)

                    #targetが最終的におきたいx座標よりも左
                    elif target_pos[1] < pos[1]:
                        #targetの上の座標にchoice(16)を置く
                        if target_pos[0] == choice_pos[0]:
                            target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                        else:
                            while target_pos[0]-1 != choice_pos[0]:
                                target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                        #targetの右上にchoice(16)を置く
                        if target_pos[1] >= choice_pos[1]:
                            while target_pos[1]+1 != choice_pos[1]:
                                target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                        else:
                            while target_pos[1]+1 != choice_pos[1]:
                                target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)

                        #targetを置きたい座標のx座標と同じになるまで移動
                        target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                        while target_pos[1] != pos[1]:
                            target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)

                        #targetの上にchoic(16)を置く
                        target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)

                    #targetが最終的におきたいx座標と同じ
                    else:
                        #targetの上の座標にchoice(16)を置く
                        if target_pos[0] == choice_pos[0]:
                            target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                        else:
                            while target_pos[0]-1 != choice_pos[0]:
                                target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)

                        #targetの上にchoiceを置く
                        if target_pos[1] < choice_pos[1]:
                            while target_pos[1] != choice_pos[1]:
                                target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)   
                        elif target_pos[1] > choice_pos[1]:
                            while target_pos[1] != choice_pos[1]:
                                target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)   

                    #targetを置きたい座標のy座標になるまで移動
                    if target_pos[0] != pos[0]:
                        target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                        while target_pos[0] != pos[0]:
                            target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                
                #最終的に置きたい位置が右から2列目
                elif j == row - 2:
                    #targetが最終的におきたいx座標よりも左
                    if target_pos[1] < pos[1]+1:
                        #targetの上の座標にchoice(16)を置く
                        if target_pos[0] == choice_pos[0]:
                            target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                        else:
                            while target_pos[0]-1 != choice_pos[0]:
                                target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                        #targetの右上にchoice(16)を置く
                        if target_pos[1] >= choice_pos[1]:
                            while target_pos[1]+1 != choice_pos[1]:
                                target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                        else:
                            while target_pos[1]+1 != choice_pos[1]:
                                target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)

                        #targetを置きたい座標のx座標と同じになるまで移動
                        target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                        while target_pos[1] != pos[1]+1:
                            target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)

                    #targetが最終的におきたいx座標の右と同じ
                    elif target_pos[1] == pos[1]+1:
                        #targetの上の座標にchoice(16)を置く
                        if target_pos[0] == choice_pos[0]:
                            target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                        else:
                            while target_pos[0]-1 != choice_pos[0]:
                                target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                        #targetの上にchoice(16)を移動
                        while target_pos[1] != choice_pos[1]:
                            target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)

                    #targetを最終的に置きたいy座標まで移動
                    target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                    while target_pos[0] != pos[0]:
                        target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)


                #最終的に置きたい位置が右端
                elif j == row - 1:
                    #targetが最終的におきたいx座標よりも左
                    if target_pos[1] < pos[1]:
                        #targetの上の座標にchoice(16)を置く
                        if target_pos[0] == choice_pos[0]:
                            target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                        else:
                            while target_pos[0]-1 != choice_pos[0]:
                                target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                        #targetの右上にchoice(16)を置く
                        if target_pos[1] >= choice_pos[1]:
                            while target_pos[1]+1 != choice_pos[1]:
                                target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                        else:
                            while target_pos[1]+1 != choice_pos[1]:
                                target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)

                        #targetを置きたい座標のx座標と同じになるまで移動
                        target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                        while target_pos[1] != pos[1]:
                            target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                            target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)

                    #targetが最終的におきたいx座標と同じ
                    elif target_pos[1] == pos[1]:
                        #targetの上の座標にchoice(16)を置く
                        if target_pos[0] == choice_pos[0]:
                            target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                        else:
                            while target_pos[0]-1 != choice_pos[0]:
                                target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                        #targetの上にchoice(16)を移動
                        while target_pos[1] != choice_pos[1]:
                            target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                    
                    #targetを最終的に置きたいy座標まで移動
                    target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                    while target_pos[0] != pos[0]+1:
                        target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                        target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)
                    
                    #3,4を最終的におきたい座標となるよう移動
                    target_pos, choice_pos, exchange = left(target_num, choice_num, exchange)
                    target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                    target_pos, choice_pos, exchange = up(target_num, choice_num, exchange)
                    target_pos, choice_pos, exchange = right(target_num, choice_num, exchange)
                    target_pos, choice_pos, exchange = down(target_num, choice_num, exchange)

            print("交換回数：" + str(exchange))    

            print(split_list)
            print()
            print("       ↓")
            print()
            

    #さいごの2行（たいち）
    

    return exchange


split_list = copy.copy(copy_list)

print(split_list)
print()
print("       ↓")
print()

exchange = 0

exchange = move(split_list, exchange)
print("交換回数：" + str(exchange))
print(split_list)

[[ 1  2  9  3]
 [ 5  6  7  8]
 [15 13 14 16]
 [10  4 12 11]]

       ↓

target_num = 1----------------------------------------------------------
[[ 1  2  9  3]
 [ 5  6  7  8]
 [15 13 16 14]
 [10  4 12 11]]

[[ 1  2  9  3]
 [ 5  6  7  8]
 [15 16 13 14]
 [10  4 12 11]]

[[ 1  2  9  3]
 [ 5 16  7  8]
 [15  6 13 14]
 [10  4 12 11]]

[[ 1 16  9  3]
 [ 5  2  7  8]
 [15  6 13 14]
 [10  4 12 11]]

交換回数：4
[[ 1 16  9  3]
 [ 5  2  7  8]
 [15  6 13 14]
 [10  4 12 11]]

       ↓

target_num = 2----------------------------------------------------------
[[ 1  9 16  3]
 [ 5  2  7  8]
 [15  6 13 14]
 [10  4 12 11]]

[[ 1  9  7  3]
 [ 5  2 16  8]
 [15  6 13 14]
 [10  4 12 11]]

[[ 1  9 16  3]
 [ 5  2  7  8]
 [15  6 13 14]
 [10  4 12 11]]

[[ 1 16  9  3]
 [ 5  2  7  8]
 [15  6 13 14]
 [10  4 12 11]]

[[ 1  2  9  3]
 [ 5 16  7  8]
 [15  6 13 14]
 [10  4 12 11]]

交換回数：7
[[ 1  2  9  3]
 [ 5 16  7  8]
 [15  6 13 14]
 [10  4 12 11]]

       ↓

target_num = 3----------------------------------------------------