In [73]:
import numpy as np
import random
import copy

# ↓問題生成

In [74]:
def puzzle_generation(puzzle_board, issue):
    #ファイル読み込み
    f = open(issue, 'r', encoding='UTF-8')
    data = f.readlines()
    f.close()


    #問題フォーマットの1行目の読み取り ----------------------------------------------------------------------------------------
    s0 = data[0].rstrip('\n').rstrip(',')
    l0 = [int(x.strip()) for x in s0.split(',')]

    colmun = l0[0]              #列
    row = l0[1]                 #行
    selection_cost = l0[2]      #選択コスト

    #スライドパズルの盤面の読み取り
    for i in range(1, row+1):
        row_data = data[i].rstrip('\n').rstrip(',')
        line_data = [int(x.strip()) for x in row_data.split(',')]
        row_array = np.array(line_data)
        if i == 1:
            puzzle_board = row_array
        else:
            puzzle_board = np.vstack((puzzle_board, row_array))


    #ランダム生成 ---------------------------------------------------------------------------------------------------------
    # random_num = random.sample(range(1, colmun*row+1), colmun*row)
    # random_list = np.array(random_num)
    # puzzle_board = random_list.reshape(colmun, row)


    return puzzle_board, colmun, row, selection_cost

# ↓移動関数

In [75]:
#選択画像を上に移動
def up():

IndentationError: expected an indented block (<ipython-input-75-a93b1bc16aef>, line 2)

In [76]:
#選択画像を下に移動
def down():

IndentationError: expected an indented block (<ipython-input-76-873a4cac58dc>, line 2)

In [77]:
#選択画像を左に移動
def left():

IndentationError: expected an indented block (<ipython-input-77-d63f6356a2c4>, line 2)

In [78]:
#選択画像を右に移動
def right():

IndentationError: expected an indented block (<ipython-input-78-ed3cd70b0384>, line 2)

# ↓回答書き込み

In [79]:
def answer_writing(selection_position, exchange_times, exchange_operation):
    f = open('answer.txt', 'w')

    f.write(str(selection_position[0]) + str(selection_position[1]) + '\n')
    f.write(str(exchange_times) + '\n')
    f.write(exchange_operation + '\n')    

    f.close()

# ↓それぞれの処理

In [80]:
# 2行を除いた盤面の並び替え(たくと)
def puzzle_board_sort_top(puzzle_board, selection_times, exchange_times, exchange_operation):
    print('colmun(列→)：' + str(colmun))
    print('row(行↓)：' + str(row))
    print('selection_cost(選択コスト)：' + str(selection_cost) + '\n')


In [81]:
# 下2行の右4マスを除いた盤面の並び替え(たいち)
def puzzle_board_sort_bottom_left(puzzle_board, selection_times, exchange_times, exchange_operation):
    print("がんば!")

In [82]:
# 右下4ますの並び替え(しのべー)
def puzzle_board_sort_bottom_right(puzzle_board, selection_times, exchange_times, exchange_operation):
    #選択画像変更次には answer_writing を実行して欲しい

    print("がんば!")


In [83]:
# 上3つをまとめたもの
def puzzle_board_sort(puzzle_board):
    selection_times = 0         #選択回数
    exchange_times = 0          #交換回数
    exchange_operation = ""     #交換操作

    #たくと担当
    puzzle_board_sort_top(puzzle_board, selection_times, exchange_times, exchange_operation)
    #たいち担当
    puzzle_board_sort_bottom_left(puzzle_board, selection_times, exchange_times, exchange_operation)
    #しのべー担当
    puzzle_board_sort_bottom_right(puzzle_board, selection_times, exchange_times, exchange_operation)

# メイン関数

In [84]:
puzzle_board =  np.array([])    #現在の盤面を表す配列

#問題盤面生成
puzzle_board, colmun, row, selection_cost = puzzle_generation(puzzle_board, 'issue/4x4.txt')

print('colmun(列→)：' + str(colmun))
print('row(行↓)：' + str(row))
print('selection_cost(選択コスト)：' + str(selection_cost) + '\n')
print(puzzle_board)


#並び替え
puzzle_board_sort(puzzle_board)

colmun(列→)：4
row(行↓)：4
selection_cost(選択コスト)：2

[[11  9  5  8]
 [12  4  7 10]
 [15  3  1 13]
 [14  2 16  6]]
colmun(列→)：4
row(行↓)：4
selection_cost(選択コスト)：2

がんば!
がんば!
